# Which CT-to-3-channel strategy (and which backbone) best recognises abnormality patterns?

**Question.** DINOv2-S / DINOv3-S are standard 3-channel vision backbones; a chest CT slice is single-channel HU, so a strategy is needed to fill those 3 channels. DALE-CT-0, by contrast, is a CT-specific backbone that takes a single HU-windowed channel natively. This notebook compares **9 methods** purely on how well their frozen features support recognising the 18 CT-RATE abnormality labels - no domain-gap analysis and no compute-cost comparison here (see `CT_Domain_Gap_Analysis.ipynb` for those).

| # | Method | Channels | Backbone |
|---|---|---|---|
| 1-4 | `same` / `windows` / `adjacent` / `window_edge` | 3 (see below) | DINOv2-S |
| 5-8 | `same` / `windows` / `adjacent` / `window_edge` | 3 (see below) | DINOv3-S |
| 9 | `dale` (native) | 1 (DALE-CT-0's own HU window) | DALE-CT-0 (ViT-L, self-supervised on CT-RATE) |

3-channel strategies (all 4 use the exact same sampled slice indices per scan, so they are paired):
* `same` - one lung-windowed slice, replicated x3
* `windows` - the same slice through 3 clinical HU windows (lung / mediastinal / bone)
* `adjacent` - 3 consecutive slices (i-1, i, i+1), each lung-windowed
* `window_edge` - lung window, mediastinal window, Sobel edge-magnitude of the lung window

All 9 methods sample slices with the **same** slab logic (`CCE_SLAB_MM` mm per slice, default 12mm), so every method is compared on the same anatomical positions.

**Evaluation**: ~`N_CTRATE` CT-RATE validation scans (stratified by vendor x kernel, same selection code as `CT_Domain_Gap_Analysis.ipynb`) with their official 18-label annotations. A cross-validated logistic-regression probe and a k-NN probe (both frozen-feature, standard self-supervised-evaluation protocol) give macro AUROC per method; the **same** `GroupKFold` splits (by patient) are reused for every method and every label, so the comparison is paired, and a Wilcoxon/bootstrap/FDR pipeline tells you which differences are real.

### Setup
* Hugging Face token (secret `HF_TOKEN` on Colab, or `HF_TOKEN` env var) with access to the gated `ibrahimhamamci/CT-RATE` dataset. DINOv3 weights are also gated (accept the licence on its model page first). DINOv2 and DALE-CT-0 weights are public.
* GPU runtime recommended. Everything is cached under `channel_encoding_outputs/cache`, so re-runs are quick.
* Set `DRY_RUN_RANDOM_WEIGHTS = True` (or env `CCE_DRY_RUN=1`) to test the plumbing with random weights (results meaningless). **Tip**: for a quick local test, also set `CCE_N_CTRATE` to a small number - `huggingface_hub` can silently reuse a cached login token even with `HF_TOKEN` unset, so "no token" is not a reliable way to skip CT-RATE downloads.

**Licences:** CT-RATE CC-BY-NC-SA-4.0 (research use only). DINOv2 Apache-2.0. DALE-CT weights CC-BY-NC-SA-4.0. DINOv3 is released under Meta's own licence - read it before using results outside research.

## 1. Configuration

In [1]:
import os, sys, re, gc, json, time, shutil, warnings, datetime as dt
from pathlib import Path
warnings.filterwarnings("ignore")

IN_COLAB = "google.colab" in sys.modules
def _env(name, default=None, cast=str):
    v = os.environ.get(name)
    return default if v in (None, "") else cast(v)

# ------------------------------ USER SETTINGS ------------------------------
N_CTRATE = _env("CCE_N_CTRATE", 200, int)                # CT-RATE validation scans (unique patients), stratified by vendor x kernel
N_CTRATE_PAIRS = 0                                        # sibling reconstructions are not used in this notebook
CTRATE_SEED = 0
CTRATE_MAX_VOXELS = 512 * 512 * 700                       # RAM guard (12 GB Colab)
DEVICE = "auto"                                           # "auto" -> cuda if available

DINO_MODELS = {                                           # timm checkpoint ids (confirmed to exist in timm 1.0.30)
    "dino2": _env("CCE_DINOV2_MODEL", "vit_small_patch14_dinov2.lvd142m"),    # public, Apache-2.0
    "dino3": _env("CCE_DINOV3_MODEL", "vit_small_patch16_dinov3.lvd1689m"),   # gated (Meta's DINOv3 licence) - accept it on the HF model page, then set HF_TOKEN
}
STRATEGIES = ("same", "windows", "adjacent", "window_edge")
DALE_MODEL = _env("CCE_DALE_MODEL", "Kentucky-Open-Science/DALE-CT-0")        # 1-channel, self-supervised on CT-RATE; public

CCE_SLAB_MM = _env("CCE_SLAB_MM", 12.0, float)            # one slice per N mm slab - SAME for every method (DINO strategies and DALE), so slice positions are identical
CCE_MAX_SLICES = _env("CCE_MAX_SLICES", None, int)        # cap sampled slices per scan (quick tests)
CCE_BATCH_SLICES = _env("CCE_BATCH_SLICES", 16, int)      # slices per backbone forward-pass chunk

PROBE_FOLDS = 5                                           # group k-fold splits (by patient), shared by every method and every label
MIN_POS = 5                                               # a label needs >= this many positives (and negatives) to be probed at all
N_BOOT = 2000

DELETE_RAW_AFTER_EMBED = True
DRY_RUN_RANDOM_WEIGHTS = _env("CCE_DRY_RUN", "0") == "1"
HF_TOKEN = os.environ.get("HF_TOKEN")
# ---------------------------------------------------------------------------

if IN_COLAB:
    from google.colab import drive
    drive.mount("/content/drive")
    BASE_DIR = "/content/drive/MyDrive/NHRD - Local Sample"
    WORK_DIR = "/content/channel_encoding_work"
    if not HF_TOKEN:
        try:
            from google.colab import userdata
            HF_TOKEN = userdata.get("HF_TOKEN")
        except Exception:
            pass
else:
    BASE_DIR = _env("CCE_BASE_DIR", os.path.expanduser("~/NHRD - Local Sample"))
    WORK_DIR = _env("CCE_WORK_DIR", os.path.expanduser("~/channel_encoding_work"))

OUTPUT_DIR = Path(_env("CCE_OUTPUT_DIR", f"{BASE_DIR}/channel_encoding_outputs")) / ("dryrun" if DRY_RUN_RANDOM_WEIGHTS else "")
CACHE_DIR = OUTPUT_DIR / "cache"
RAW_DIR = Path(WORK_DIR) / "raw"
WEIGHTS_DIR = Path(WORK_DIR) / "weights"
for d in (OUTPUT_DIR / "figures", CACHE_DIR, RAW_DIR, WEIGHTS_DIR):
    d.mkdir(parents=True, exist_ok=True)
print("Colab:", IN_COLAB, "| dry run:", DRY_RUN_RANDOM_WEIGHTS, "| N_CTRATE:", N_CTRATE)
for k in ("BASE_DIR", "OUTPUT_DIR", "WORK_DIR"):
    print(f"{k:11s}", globals()[k])

Mounted at /content/drive
Colab: True | dry run: False | N_CTRATE: 200
BASE_DIR    /content/drive/MyDrive/NHRD - Local Sample
OUTPUT_DIR  /content/drive/MyDrive/NHRD - Local Sample/channel_encoding_outputs
WORK_DIR    /content/channel_encoding_work

## 2. Environment
No CT-CLIP/CTViT repo and no DICOM reading needed here - this notebook only reads CT-RATE NIfTI volumes (already in the training arrangement) and runs `timm` backbones (DINOv2-S, DINOv3-S) plus DALE-CT-0.

In [2]:
def pip_install(*pkgs):
    import subprocess
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", *pkgs], check=True)

try:
    import torch
except ImportError:
    pip_install("torch"); import torch
pip_install("nibabel", "huggingface_hub", "timm", "safetensors", "scikit-learn", "scipy", "requests", "pandas", "matplotlib")

import numpy as np, pandas as pd, requests
import torch.nn.functional as F
import matplotlib
import matplotlib.pyplot as plt
from IPython.display import display, Markdown
warnings.filterwarnings("ignore")

DEV = ("cuda" if torch.cuda.is_available() else "cpu") if DEVICE == "auto" else DEVICE
print("torch", torch.__version__, "| device:", DEV, "| GPU:", torch.cuda.get_device_name(0) if DEV == "cuda" else "-", "| threads:", torch.get_num_threads())
if HF_TOKEN:
    try:
        from huggingface_hub import login
        login(token=HF_TOKEN, add_to_git_credential=False)
    except Exception as e:
        print("huggingface_hub login failed (gated DINOv3/CT-RATE downloads may fail):", repr(e)[:200])

torch 2.11.0+cu128 | device: cuda | GPU: Tesla T4 | threads: 1

## 3. Reading CT-RATE volumes
CT-RATE NIfTI arrays are already stored in the arrangement CT-CLIP/DALE-CT-0 were trained on, so no DICOM/orientation handling is needed here (unlike the domain-gap notebook, which also ingests raw local DICOMs). **Reused verbatim from `CT_Domain_Gap_Analysis.ipynb`**: `_crop_pad_axis`, `preprocess_volume`, `TARGET_SPACING`/`TARGET_SHAPE`.

In [3]:
TARGET_SPACING = (1.5, 0.75, 0.75)      # (z, height, width) mm
TARGET_SHAPE = (240, 480, 480)          # voxels

def _crop_pad_axis(t, dim, target):
    n = t.shape[dim]
    start = max((n - target) // 2, 0)
    t = t.narrow(dim, start, min(start + target, n) - start)
    before = (target - t.shape[dim]) // 2
    return t, (before, target - t.shape[dim] - before)

def preprocess_volume(vol_B, spacing_B):
    """Official CT-CLIP preprocessing of an already CT-RATE-arranged HU volume -> float32 (1, 240, 480, 480), air/padding = -1."""
    v = torch.from_numpy(np.clip(vol_B, -1000, 1000))[None, None]
    new_shape = [int(n * cur / tgt) for n, cur, tgt in zip(v.shape[2:], spacing_B, TARGET_SPACING)]
    v = F.interpolate(v, size=new_shape, mode="trilinear", align_corners=False)[0, 0] / 1000.0
    pads = []
    for dim, tgt in enumerate(TARGET_SHAPE):
        v, p = _crop_pad_axis(v, dim, tgt)
        pads.append(p)
    v = F.pad(v, (*pads[2], *pads[1], *pads[0]), value=-1.0)
    assert tuple(v.shape) == TARGET_SHAPE, v.shape
    return v.unsqueeze(0).contiguous()

## 4. CT-RATE scan selection
**Reused verbatim**: `select_ctrate` (stratified vendor x kernel round-robin), `hf_fetch`/`ctrate_rel_path`/`download_ctrate`, `vendor_group`/`kernel_family`, `read_ctrate_volume`. Only the `ctrate` cohort is used in this notebook (no local/LIDC scans - they played no role once domain-gap analysis was taken out of scope).

In [4]:
CT_REPO = "ibrahimhamamci/CT-RATE"
CTRATE_DIR = Path(WORK_DIR) / "ctrate_meta"
CTRATE_DIR.mkdir(parents=True, exist_ok=True)
_num = lambda s: (re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", str(s)) or ["nan"])[0]

def hf_fetch(rel, local_dir):
    dst = Path(local_dir) / rel
    if dst.exists() and dst.stat().st_size > 0:
        return dst
    from huggingface_hub import hf_hub_download
    return Path(hf_hub_download(repo_id=CT_REPO, repo_type="dataset", filename=rel, token=HF_TOKEN or None, local_dir=str(local_dir)))

def ctrate_rel_path(name):
    m = re.match(r"valid_(\d+)_([a-z]+)_(\d+)\.nii\.gz$", name)
    return f"dataset/valid_fixed/valid_{m[1]}/valid_{m[1]}_{m[2]}/{name}"

def vendor_group(s):
    s = str(s).lower()
    return "Philips" if "philips" in s else "Siemens" if "siemens" in s else "PNMS" if "pnms" in s else "Toshiba" if ("toshiba" in s or "canon" in s) else "GE" if "ge " in s or s.startswith("ge") else str(s)

def kernel_family(k):
    k = str(k).strip("[]' ").split("'")[0].split(",")[0].strip()
    return k or "?"

def select_ctrate(meta, labels_idx, nochest, n_total, n_pairs, seed, max_voxels):
    """Stratified (vendor x kernel) round-robin selection of unique patients. Returns (chosen_names, sibling_map, meta_df)."""
    M = meta.copy()
    M["xy"] = M.XYSpacing.map(lambda s: float(_num(s))); M["z"] = pd.to_numeric(M.ZSpacing, errors="coerce")
    M["voxels"] = M.Rows * M.Columns * M.NumberofSlices; M["zext"] = M.NumberofSlices * M.z
    M["patient"] = M.index.str.extract(r"valid_(\d+)_", expand=False); M["acq"] = M.index.str.extract(r"valid_(\d+_[a-z]+)_", expand=False)
    M["vendor"] = M.Manufacturer.map(vendor_group); M["kfam"] = M.ConvolutionKernel.map(kernel_family)
    ok = M[~M.index.str.replace(".nii.gz", "", regex=False).isin(nochest) & M.z.notna() & M.xy.notna() & (M.voxels <= max_voxels) & (M.zext >= 150) & M.index.isin(labels_idx)]
    rng = np.random.default_rng(seed)
    pool = ok.sample(frac=1.0, random_state=seed).sort_values("voxels", kind="stable").groupby("patient").head(1)
    strata = {k: list(g.index) for k, g in pool.groupby(["vendor", "kfam"])}
    for k in strata:
        rng.shuffle(strata[k])
    order = sorted(strata, key=lambda k: -len(strata[k]))
    chosen = []
    while len(chosen) < n_total and any(strata.values()):
        for k in order:
            if strata[k] and len(chosen) < n_total:
                chosen.append(strata[k].pop())
    sib = {}
    if n_pairs:
        cand = [n for n in chosen if len(ok[(ok.acq == M.loc[n, "acq"]) & (ok.index != n)]) > 0]
        rng.shuffle(cand)
        for n in cand[:n_pairs]:
            others = ok[(ok.acq == M.loc[n, "acq"]) & (ok.index != n)]
            sib[n] = others.sort_values("voxels").index[0]
    return sorted(chosen), sib, M

PATHOLOGIES = ['Medical material', 'Arterial wall calcification', 'Cardiomegaly', 'Pericardial effusion', 'Coronary artery wall calcification', 'Hiatal hernia', 'Lymphadenopathy', 'Emphysema',
               'Atelectasis', 'Lung nodule', 'Lung opacity', 'Pulmonary fibrotic sequela', 'Pleural effusion', 'Mosaic attenuation pattern', 'Peribronchial thickening', 'Consolidation',
               'Bronchiectasis', 'Interlobular septal thickening']

ITEMS = []
CT_META = ct_labels = None
try:
    ct_meta = pd.read_csv(hf_fetch("dataset/metadata/validation_metadata.csv", CTRATE_DIR)).set_index("VolumeName")
    ct_labels = pd.read_csv(hf_fetch("dataset/multi_abnormality_labels/valid_predicted_labels.csv", CTRATE_DIR)).set_index("VolumeName")
    ct_nochest = set(re.findall(r"(valid_\d+_[a-z]+_\d+)\.nii\.gz", hf_fetch("dataset/metadata/no_chest_valid.txt", CTRATE_DIR).read_text()))
    prim, sibs, CT_META = select_ctrate(ct_meta, set(ct_labels.index), ct_nochest, N_CTRATE, N_CTRATE_PAIRS, CTRATE_SEED, CTRATE_MAX_VOXELS)
    for n in prim:
        pid = re.match(r"valid_(\d+)_", n)[1]
        ITEMS.append(dict(cohort="ctrate", id=n.replace(".nii.gz", ""), name=n, group=f"ctrate_{pid}", primary=True))
    sel = CT_META.loc[prim]
    print(f"CT-RATE: {len(prim)} unique patients selected")
    display(pd.crosstab(sel.vendor, sel.kfam))
except Exception as e:
    print("CT-RATE could not be set up:", repr(e)[:300], "\n-> check HF_TOKEN and that you accepted the dataset terms. This notebook cannot run without it.")

print("total volumes to process:", len(ITEMS))

validation_metadata.csv:   0%|          | 0.00/948k [00:00<?, ?B/s]

valid_predicted_labels.csv:   0%|          | 0.00/174k [00:00<?, ?B/s]

no_chest_valid.txt:   0%|          | 0.00/1.83k [00:00<?, ?B/s]

CT-RATE: 200 unique patients selected

kfam      A   B  Bl56f  Bl57d  Br36d  Br40f  Br44f  Br60f  EA  L  SA  SB
vendor
PNMS      0   0      0      0      0      0      0      0  23  0   9   1
Philips  23  24      0      0      0      0      0      0   0  1   0   0
Siemens   0   0     23     23     23     23      4     23   0  0   0   0

total volumes to process: 200

In [5]:
def read_ctrate_volume(name, raw_dir):
    """CT-RATE NIfTI -> (vol (k, i, j) = (Z, LEFT axis, POSTERIOR axis) HU float32, spacing, meta)."""
    import nibabel as nib
    nii = nib.load(str(Path(raw_dir) / ctrate_rel_path(name)))
    vol = nii.get_fdata().astype(np.float32)
    row = CT_META.loc[name]
    frac_air = float(((vol > -1050) & (vol < -950)).mean())
    if frac_air < 0.001:
        vol = vol * float(row.RescaleSlope) + float(row.RescaleIntercept)
    xy, z = float(_num(row.XYSpacing)), float(row.ZSpacing)
    meta = dict(vendor=vendor_group(row.Manufacturer), kernel=kernel_family(row.ConvolutionKernel), z_spacing=z, xy_spacing=xy)
    return vol.transpose(2, 0, 1), (z, xy, xy), meta

def download_ctrate(name, raw_dir):
    return hf_fetch(ctrate_rel_path(name), raw_dir)

## 5. Channel-construction strategies and the two extractors
All 9 methods start from the **same sampled slice indices** per scan (one slice per `CCE_SLAB_MM` mm) via `slab_slice_idx`, so the comparison is paired - differences come only from how each method represents those slices, not from which anatomy was sampled.

| Strategy | Channel 1 | Channel 2 | Channel 3 |
|---|---|---|---|
| `same` | lung window | lung window (copy) | lung window (copy) |
| `windows` | lung window | mediastinal window | bone window |
| `adjacent` | slice i-1 (lung window) | slice i (lung window) | slice i+1 (lung window) |
| `window_edge` | lung window | mediastinal window | Sobel edge-magnitude of the lung window |

Windows are standard clinical HU windows (center, width): lung (-600, 1500), mediastinal (40, 400), bone (400, 1800), each mapped to [0,1]. DALE-CT-0 instead uses its own 1-channel preprocessing exactly as published (HU clipped to [-997, 888], min-max then z-scored with its model card's mean/std) - it is not forced through the clinical windows above, since the point is to compare it as its own native method.

In [6]:
WINDOWS = {"lung": (-600.0, 1500.0), "mediastinal": (40.0, 400.0), "bone": (400.0, 1800.0)}
_SOBEL_X = torch.tensor([[-1., 0., 1.], [-2., 0., 2.], [-1., 0., 1.]])
_SOBEL_Y = _SOBEL_X.t()

def window_hu(hu, center, width):
    lo = center - width / 2.0
    return ((hu - lo) / width).clamp(0.0, 1.0)

def sobel_edge_map(img):
    """img: (N,1,H,W) in [0,1] -> edge magnitude in [0,1], normalised per-slice by its own 99th percentile."""
    gx = F.conv2d(F.pad(img, (1, 1, 1, 1), mode="replicate"), _SOBEL_X.view(1, 1, 3, 3))
    gy = F.conv2d(F.pad(img, (1, 1, 1, 1), mode="replicate"), _SOBEL_Y.view(1, 1, 3, 3))
    mag = torch.sqrt(gx * gx + gy * gy + 1e-12)
    q = torch.quantile(mag.flatten(1), 0.99, dim=1).clamp_min(1e-6).view(-1, 1, 1, 1)
    return (mag / q).clamp(0.0, 1.0)

def slab_slice_idx(x, slab_mm=CCE_SLAB_MM, max_slices=CCE_MAX_SLICES, spacing_mm=TARGET_SPACING[0]):
    """x: (Z,H,W) model-input tensor, HU/1000 in [-1,1], padding=-1. -> (idx, valid): idx = one slice per slab_mm, centred; valid = all non-padding slice indices.
    Shared by every method in this notebook (DINO strategies and DALE), so all 9 feature spaces are compared on identical anatomical positions."""
    valid = torch.nonzero(x.amax(dim=(1, 2)) > -0.99).flatten()
    step = max(1, int(round(slab_mm / spacing_mm)))
    idx = valid[step // 2::step]
    if max_slices and len(idx) > max_slices:
        idx = idx[np.linspace(0, len(idx) - 1, max_slices).astype(int)]
    return idx, valid

def build_channels(x, idx, valid, strategy):
    """x: (Z,H,W) tensor in [-1,1] (HU/1000). -> (S,3,H,W) in [0,1], one of the 4 DINO-side strategies."""
    hu = x[idx] * 1000.0
    lung = window_hu(hu, *WINDOWS["lung"])
    if strategy == "same":
        return torch.stack([lung, lung, lung], dim=1)
    if strategy == "windows":
        med = window_hu(hu, *WINDOWS["mediastinal"]); bone = window_hu(hu, *WINDOWS["bone"])
        return torch.stack([lung, med, bone], dim=1)
    if strategy == "adjacent":
        lo, hi = int(valid[0]), int(valid[-1])
        idx_m1 = (idx - 1).clamp(lo, hi); idx_p1 = (idx + 1).clamp(lo, hi)
        lung_m1 = window_hu(x[idx_m1] * 1000.0, *WINDOWS["lung"]); lung_p1 = window_hu(x[idx_p1] * 1000.0, *WINDOWS["lung"])
        return torch.stack([lung_m1, lung, lung_p1], dim=1)
    if strategy == "window_edge":
        med = window_hu(hu, *WINDOWS["mediastinal"]); edge = sobel_edge_map(lung[:, None])[:, 0]
        return torch.stack([lung, med, edge], dim=1)
    raise ValueError(f"unknown strategy: {strategy}")

class DinoChannelExtractor:
    """Both DINO backbones x all 4 channel strategies. .embed(t, want) returns only the requested '{backbone}_{strategy}' keys."""
    name = "dino_channel"
    keys = tuple(f"{bk}_{st}" for bk in DINO_MODELS for st in STRATEGIES)

    def __init__(self, dev):
        import timm
        self.dev = dev
        self.models, self.norm, self.tgt_size = {}, {}, {}
        for bk, model_name in DINO_MODELS.items():
            try:
                if DRY_RUN_RANDOM_WEIGHTS:
                    m = timm.create_model(model_name, pretrained=False, num_classes=0, dynamic_img_size=True).eval()
                    torch.manual_seed(0); print(f"  {bk}: RANDOM weights (dry run) [{model_name}]")
                else:
                    m = timm.create_model(model_name, pretrained=True, num_classes=0, dynamic_img_size=True).eval()
                    print(f"  {bk}: pretrained weights loaded [{model_name}]")
                cfg = getattr(m, "pretrained_cfg", {}) or {}
                mean = torch.tensor(cfg.get("mean", (0.485, 0.456, 0.406))).view(3, 1, 1)
                std = torch.tensor(cfg.get("std", (0.229, 0.224, 0.225))).view(3, 1, 1)
                patch = m.patch_embed.patch_size[0]                          # dynamic_img_size still requires H/W divisible by the patch size
                self.tgt_size[bk] = (TARGET_SHAPE[1] // patch) * patch       # nearest multiple of patch size <= 480 (476 for patch14, 480 for patch16)
                m.to(dev)
                self.models[bk] = m; self.norm[bk] = (mean, std)
            except Exception as e:
                print(f"  {bk} FAILED to load and is dropped: {repr(e)[:300]}")
        assert self.models, "no DINO backbone could be loaded"

    @torch.no_grad()
    def embed(self, t, want=None):
        want = set(want) if want is not None else set(self.keys)
        x = t[0]
        idx, valid = slab_slice_idx(x)
        out = {}
        for strategy in STRATEGIES:
            need_bks = [bk for bk in self.models if f"{bk}_{strategy}" in want]
            if not need_bks:
                continue
            ch = build_channels(x, idx, valid, strategy)                        # (S,3,H,W) in [0,1], CPU
            for bk in need_bks:
                size = self.tgt_size[bk]
                ch_bk = F.interpolate(ch, size=(size, size), mode="bilinear", align_corners=False) if size != ch.shape[-1] else ch
                mean, std = self.norm[bk]
                z = (ch_bk - mean) / std
                outs = []
                for i in range(0, len(z), CCE_BATCH_SLICES):
                    b = z[i:i + CCE_BATCH_SLICES].to(self.dev)
                    with torch.autocast("cuda", dtype=torch.float16, enabled=(self.dev == "cuda")):
                        outs.append(self.models[bk](b).float().cpu())
                out[f"{bk}_{strategy}"] = torch.cat(outs).mean(0).numpy()
        return out

def load_safetensors_strict(model, path, name):
    from safetensors.torch import load_file
    res = model.load_state_dict(load_file(str(path)), strict=True)
    print(f"  {name}: weights loaded strictly ({len(model.state_dict())} tensors)")

def hub_file(repo, filename, repo_type="model", token=None):
    from huggingface_hub import hf_hub_download
    return Path(hf_hub_download(repo_id=repo, filename=filename, repo_type=repo_type, token=token, local_dir=str(WEIGHTS_DIR / repo.replace("/", "__"))))

class DaleExtractor:
    """DALE-CT-0's own 1-channel method: same sampled slice positions (slab_slice_idx), its own HU window/normalisation, no clinical-window substitution."""
    name, keys = "dale", ("dale",)
    CLIP_MIN, CLIP_MAX, MEAN_HU, STD_HU = -997.0, 888.0, -142.39, 360.97

    def __init__(self, dev, repo=None):
        import timm
        repo = repo or DALE_MODEL
        self.dev = dev
        self.m = timm.create_model("vit_large_patch14_dinov2", pretrained=False, num_classes=0, in_chans=1, patch_size=16, img_size=512, dynamic_img_size=True).eval()
        if DRY_RUN_RANDOM_WEIGHTS:
            torch.manual_seed(0); print("  dale: RANDOM weights (dry run)")
        else:
            load_safetensors_strict(self.m, hub_file(repo, "model.safetensors"), "dale")
        self.m.to(dev)
        rng = self.CLIP_MAX - self.CLIP_MIN
        self.nm, self.ns = (self.MEAN_HU - self.CLIP_MIN) / rng, self.STD_HU / rng

    @torch.no_grad()
    def embed(self, t, want=None):
        if want is not None and "dale" not in want:
            return {}
        x = t[0]
        idx, valid = slab_slice_idx(x)                                        # same shared slab logic as the DINO strategies
        hu = (x[idx] * 1000.0).clamp(self.CLIP_MIN, self.CLIP_MAX)
        z = (((hu - self.CLIP_MIN) / (self.CLIP_MAX - self.CLIP_MIN)) - self.nm) / self.ns
        outs = []
        for i in range(0, len(z), CCE_BATCH_SLICES):
            b = z[i:i + CCE_BATCH_SLICES, None].to(self.dev)
            with torch.autocast("cuda", dtype=torch.float16, enabled=(self.dev == "cuda")):
                outs.append(self.m(b).float().cpu())
        return {"dale": torch.cat(outs).mean(0).numpy()}

EXT = {}
for name, cls in (("dino", DinoChannelExtractor), ("dale", DaleExtractor)):
    try:
        EXT[name] = cls(DEV)
    except Exception as e:
        print(f"extractor {name} FAILED to load and is dropped: {repr(e)[:300]}")
assert EXT, "no extractor could be loaded"
KEYS_NEEDED = [k for e in EXT.values() for k in e.keys]
SPACE_OF = {k: (f"{'DINOv2-S' if k.startswith('dino2') else 'DINOv3-S'} / {k.split('_', 1)[1]}" if k != "dale" else "DALE-CT-0 (1-channel, native)") for k in KEYS_NEEDED}
print("methods under test:", KEYS_NEEDED)

model.safetensors: reconstructing file:   0%|          |  0.00B / 88.2MB

model.safetensors: downloading bytes:           |  0.00B

  dino2: pretrained weights loaded [vit_small_patch14_dinov2.lvd142m]

model.safetensors: reconstructing file:   0%|          |  0.00B / 86.4MB

model.safetensors: downloading bytes:           |  0.00B

  dino3: pretrained weights loaded [vit_small_patch16_dinov3.lvd1689m]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.21GB

model.safetensors: downloading bytes:           |  0.00B

  dale: weights loaded strictly (342 tensors)
methods under test: ['dino2_same', 'dino2_windows', 'dino2_adjacent', 'dino2_window_edge', 'dino3_same', 'dino3_windows', 'dino3_adjacent', 'dino3_window_edge', 'dale']

### Unit check: the strategies actually differ
Regression guard, run before any real extraction: `same`'s 3 channels must be identical by construction, and the other 3 DINO-side strategies must NOT be (otherwise a bug silently built 3 identical channels).

In [7]:
def _unit_check_channels():
    rng = torch.Generator().manual_seed(0)
    x = torch.rand((40, 32, 32), generator=rng) * 1.6 - 1.0           # fake volume in roughly [-1, 0.6]
    x[:6] = -1.0; x[-6:] = -1.0                                        # padding at both ends
    idx, valid = slab_slice_idx(x, slab_mm=12.0, max_slices=None)
    assert len(idx) >= 1, "no slices sampled in the unit check"
    for strat in STRATEGIES:
        ch = build_channels(x, idx, valid, strat)
        d01 = (ch[:, 0] - ch[:, 1]).abs().max().item()
        d02 = (ch[:, 0] - ch[:, 2]).abs().max().item()
        if strat == "same":
            assert d01 == 0.0 and d02 == 0.0, f"'same' strategy channels are not identical ({d01}, {d02})"
        else:
            assert d01 > 0.0 or d02 > 0.0, f"'{strat}' strategy produced 3 identical channels (likely a bug)"
    print("unit check OK: 'same' channels are identical; 'windows'/'adjacent'/'window_edge' channels differ")

_unit_check_channels()

unit check OK: 'same' channels are identical; 'windows'/'adjacent'/'window_edge' channels differ

## 6. Extraction loop (cached)
Read a CT-RATE volume (downloading on demand) -> preprocess -> every method's embedding, cached to `channel_encoding_outputs/cache/<id>.npz`. Re-running skips finished scans; adding a method later only computes the new keys.

In [8]:
PIPE_VERSION = "v1"
def _pack(**kw):
    return {k: (np.array(json.dumps(v)) if isinstance(v, (dict, list)) else np.asarray(v)) for k, v in kw.items()}

def load_cache(it):
    p = CACHE_DIR / f"{it['id']}.npz"
    if not p.exists():
        return {}
    d = dict(np.load(p, allow_pickle=False))
    return d if str(d.get("pipe", "")) == PIPE_VERSION else {}

def obtain_volume(it):
    p = download_ctrate(it["name"], RAW_DIR)
    vB, spB, meta = read_ctrate_volume(it["name"], RAW_DIR)
    return vB, spB, meta, p

def process_item(it):
    have = load_cache(it)
    need = [k for k in KEYS_NEEDED if k not in have]
    if not need and "meta" in have:
        return have
    vB, spB, meta, cleanup = obtain_volume(it)
    t = preprocess_volume(vB, spB); del vB
    out = dict(have)
    for e in EXT.values():
        if any(k in need for k in e.keys):
            for k, v in e.embed(t, want=need).items():
                out[k] = np.asarray(v, dtype=np.float32)
    out.update(_pack(meta={**meta, "cohort": it["cohort"]}, pipe=PIPE_VERSION))
    np.savez_compressed(CACHE_DIR / f"{it['id']}.npz", **out)
    if cleanup is not None and DELETE_RAW_AFTER_EMBED:
        try:
            shutil.rmtree(cleanup) if Path(cleanup).is_dir() else Path(cleanup).unlink()
        except Exception:
            pass
    return out

FAILED = {}
t_all = time.time()
for n, it in enumerate(ITEMS, 1):
    try:
        t0 = time.time(); process_item(it)
        print(f"[{n}/{len(ITEMS)}] {it['id']:<34s} {time.time() - t0:5.1f}s")
    except Exception as e:
        FAILED[it["id"]] = repr(e)[:200]; print(f"[{n}/{len(ITEMS)}] {it['id']:<34s} FAILED: {FAILED[it['id']]}")
    gc.collect()
    if DEV == "cuda":
        torch.cuda.empty_cache()
print(f"done in {(time.time() - t_all) / 60:.1f} min | failed: {len(FAILED)}")

dataset/valid_fixed/valid_1009/valid_100(…): reconstructing file:   0%|          |  0.00B /  164MB

dataset/valid_fixed/valid_1009/valid_100(…): downloading bytes:           |  0.00B

[1/200] valid_1009_a_1                      16.7s

dataset/valid_fixed/valid_1016/valid_101(…): reconstructing file:   0%|          |  0.00B / 73.1MB

dataset/valid_fixed/valid_1016/valid_101(…): downloading bytes:           |  0.00B

[2/200] valid_1016_b_1                       9.8s

dataset/valid_fixed/valid_1034/valid_103(…): reconstructing file:   0%|          |  0.00B / 78.3MB

dataset/valid_fixed/valid_1034/valid_103(…): downloading bytes:           |  0.00B

[3/200] valid_1034_a_1                       7.2s

dataset/valid_fixed/valid_1041/valid_104(…): reconstructing file:   0%|          |  0.00B / 61.2MB

dataset/valid_fixed/valid_1041/valid_104(…): downloading bytes:           |  0.00B

[4/200] valid_1041_b_2                       5.4s

dataset/valid_fixed/valid_1042/valid_104(…): reconstructing file:   0%|          |  0.00B / 69.4MB

dataset/valid_fixed/valid_1042/valid_104(…): downloading bytes:           |  0.00B

[5/200] valid_1042_a_2                       5.3s

dataset/valid_fixed/valid_1046/valid_104(…): reconstructing file:   0%|          |  0.00B / 71.2MB

dataset/valid_fixed/valid_1046/valid_104(…): downloading bytes:           |  0.00B

[6/200] valid_1046_a_2                       7.6s

dataset/valid_fixed/valid_1051/valid_105(…): reconstructing file:   0%|          |  0.00B / 61.9MB

dataset/valid_fixed/valid_1051/valid_105(…): downloading bytes:           |  0.00B

[7/200] valid_1051_a_1                       6.4s

dataset/valid_fixed/valid_1061/valid_106(…): reconstructing file:   0%|          |  0.00B / 84.1MB

dataset/valid_fixed/valid_1061/valid_106(…): downloading bytes:           |  0.00B

[8/200] valid_1061_a_1                       7.5s

dataset/valid_fixed/valid_1065/valid_106(…): reconstructing file:   0%|          |  0.00B /  120MB

dataset/valid_fixed/valid_1065/valid_106(…): downloading bytes:           |  0.00B

[9/200] valid_1065_a_2                       7.1s

dataset/valid_fixed/valid_1066/valid_106(…): reconstructing file:   0%|          |  0.00B /  163MB

dataset/valid_fixed/valid_1066/valid_106(…): downloading bytes:           |  0.00B

[10/200] valid_1066_a_2                      10.9s

dataset/valid_fixed/valid_1082/valid_108(…): reconstructing file:   0%|          |  0.00B / 93.6MB

dataset/valid_fixed/valid_1082/valid_108(…): downloading bytes:           |  0.00B

[11/200] valid_1082_b_2                       8.4s

dataset/valid_fixed/valid_1083/valid_108(…): reconstructing file:   0%|          |  0.00B / 67.5MB

dataset/valid_fixed/valid_1083/valid_108(…): downloading bytes:           |  0.00B

[12/200] valid_1083_a_2                       7.7s

dataset/valid_fixed/valid_1087/valid_108(…): reconstructing file:   0%|          |  0.00B / 77.7MB

dataset/valid_fixed/valid_1087/valid_108(…): downloading bytes:           |  0.00B

[13/200] valid_1087_a_2                       7.2s

dataset/valid_fixed/valid_1102/valid_110(…): reconstructing file:   0%|          |  0.00B /  158MB

dataset/valid_fixed/valid_1102/valid_110(…): downloading bytes:           |  0.00B

[14/200] valid_1102_a_2                      11.7s

dataset/valid_fixed/valid_1103/valid_110(…): reconstructing file:   0%|          |  0.00B / 57.8MB

dataset/valid_fixed/valid_1103/valid_110(…): downloading bytes:           |  0.00B

[15/200] valid_1103_b_2                       7.1s

dataset/valid_fixed/valid_110/valid_110_(…): reconstructing file:   0%|          |  0.00B /  160MB

dataset/valid_fixed/valid_110/valid_110_(…): downloading bytes:           |  0.00B

[16/200] valid_110_a_1                        8.9s

dataset/valid_fixed/valid_1114/valid_111(…): reconstructing file:   0%|          |  0.00B / 67.8MB

dataset/valid_fixed/valid_1114/valid_111(…): downloading bytes:           |  0.00B

[17/200] valid_1114_a_1                       6.4s

dataset/valid_fixed/valid_1126/valid_112(…): reconstructing file:   0%|          |  0.00B / 60.1MB

dataset/valid_fixed/valid_1126/valid_112(…): downloading bytes:           |  0.00B

[18/200] valid_1126_b_2                       6.8s

dataset/valid_fixed/valid_1131/valid_113(…): reconstructing file:   0%|          |  0.00B /  109MB

dataset/valid_fixed/valid_1131/valid_113(…): downloading bytes:           |  0.00B

[19/200] valid_1131_b_2                       9.2s

dataset/valid_fixed/valid_1138/valid_113(…): reconstructing file:   0%|          |  0.00B / 68.6MB

dataset/valid_fixed/valid_1138/valid_113(…): downloading bytes:           |  0.00B

[20/200] valid_1138_a_1                      10.5s

dataset/valid_fixed/valid_1145/valid_114(…): reconstructing file:   0%|          |  0.00B /  116MB

dataset/valid_fixed/valid_1145/valid_114(…): downloading bytes:           |  0.00B

[21/200] valid_1145_a_2                       6.6s

dataset/valid_fixed/valid_1146/valid_114(…): reconstructing file:   0%|          |  0.00B /  168MB

dataset/valid_fixed/valid_1146/valid_114(…): downloading bytes:           |  0.00B

[22/200] valid_1146_a_1                      10.4s

dataset/valid_fixed/valid_1167/valid_116(…): reconstructing file:   0%|          |  0.00B /  106MB

dataset/valid_fixed/valid_1167/valid_116(…): downloading bytes:           |  0.00B

[23/200] valid_1167_a_1                      11.4s

dataset/valid_fixed/valid_116/valid_116_(…): reconstructing file:   0%|          |  0.00B /  138MB

dataset/valid_fixed/valid_116/valid_116_(…): downloading bytes:           |  0.00B

[24/200] valid_116_a_2                       11.2s

dataset/valid_fixed/valid_117/valid_117_(…): reconstructing file:   0%|          |  0.00B / 72.2MB

dataset/valid_fixed/valid_117/valid_117_(…): downloading bytes:           |  0.00B

[25/200] valid_117_b_1                        6.9s

dataset/valid_fixed/valid_1188/valid_118(…): reconstructing file:   0%|          |  0.00B / 95.7MB

dataset/valid_fixed/valid_1188/valid_118(…): downloading bytes:           |  0.00B

[26/200] valid_1188_a_1                       8.4s

dataset/valid_fixed/valid_118/valid_118_(…): reconstructing file:   0%|          |  0.00B / 81.0MB

dataset/valid_fixed/valid_118/valid_118_(…): downloading bytes:           |  0.00B

[27/200] valid_118_b_1                        7.3s

dataset/valid_fixed/valid_1196/valid_119(…): reconstructing file:   0%|          |  0.00B / 98.7MB

dataset/valid_fixed/valid_1196/valid_119(…): downloading bytes:           |  0.00B

[28/200] valid_1196_a_1                       8.9s

dataset/valid_fixed/valid_1202/valid_120(…): reconstructing file:   0%|          |  0.00B / 97.5MB

dataset/valid_fixed/valid_1202/valid_120(…): downloading bytes:           |  0.00B

[29/200] valid_1202_a_1                       8.8s

dataset/valid_fixed/valid_120/valid_120_(…): reconstructing file:   0%|          |  0.00B /  106MB

dataset/valid_fixed/valid_120/valid_120_(…): downloading bytes:           |  0.00B

[30/200] valid_120_a_1                        7.7s

dataset/valid_fixed/valid_1219/valid_121(…): reconstructing file:   0%|          |  0.00B / 93.6MB

dataset/valid_fixed/valid_1219/valid_121(…): downloading bytes:           |  0.00B

[31/200] valid_1219_a_1                       6.9s

dataset/valid_fixed/valid_121/valid_121_(…): reconstructing file:   0%|          |  0.00B / 61.0MB

dataset/valid_fixed/valid_121/valid_121_(…): downloading bytes:           |  0.00B

[32/200] valid_121_a_1                        6.5s

dataset/valid_fixed/valid_1220/valid_122(…): reconstructing file:   0%|          |  0.00B / 52.0MB

dataset/valid_fixed/valid_1220/valid_122(…): downloading bytes:           |  0.00B

[33/200] valid_1220_a_2                       6.1s

dataset/valid_fixed/valid_1222/valid_122(…): reconstructing file:   0%|          |  0.00B /  147MB

dataset/valid_fixed/valid_1222/valid_122(…): downloading bytes:           |  0.00B

[34/200] valid_1222_a_2                      10.9s

dataset/valid_fixed/valid_1246/valid_124(…): reconstructing file:   0%|          |  0.00B / 98.1MB

dataset/valid_fixed/valid_1246/valid_124(…): downloading bytes:           |  0.00B

[35/200] valid_1246_a_1                       8.6s

dataset/valid_fixed/valid_1257/valid_125(…): reconstructing file:   0%|          |  0.00B / 44.5MB

dataset/valid_fixed/valid_1257/valid_125(…): downloading bytes:           |  0.00B

[36/200] valid_1257_a_1                       5.9s

dataset/valid_fixed/valid_1266/valid_126(…): reconstructing file:   0%|          |  0.00B / 42.4MB

dataset/valid_fixed/valid_1266/valid_126(…): downloading bytes:           |  0.00B

[37/200] valid_1266_a_2                       5.2s

dataset/valid_fixed/valid_1268/valid_126(…): reconstructing file:   0%|          |  0.00B / 96.5MB

dataset/valid_fixed/valid_1268/valid_126(…): downloading bytes:           |  0.00B

[38/200] valid_1268_a_2                       9.6s

dataset/valid_fixed/valid_126/valid_126_(…): reconstructing file:   0%|          |  0.00B / 88.6MB

dataset/valid_fixed/valid_126/valid_126_(…): downloading bytes:           |  0.00B

[39/200] valid_126_a_1                        8.8s

dataset/valid_fixed/valid_1270/valid_127(…): reconstructing file:   0%|          |  0.00B /  155MB

dataset/valid_fixed/valid_1270/valid_127(…): downloading bytes:           |  0.00B

[40/200] valid_1270_a_1                       8.4s

dataset/valid_fixed/valid_1279/valid_127(…): reconstructing file:   0%|          |  0.00B /  144MB

dataset/valid_fixed/valid_1279/valid_127(…): downloading bytes:           |  0.00B

[41/200] valid_1279_a_2                       9.1s

dataset/valid_fixed/valid_1280/valid_128(…): reconstructing file:   0%|          |  0.00B /  163MB

dataset/valid_fixed/valid_1280/valid_128(…): downloading bytes:           |  0.00B

[42/200] valid_1280_a_1                       8.7s

dataset/valid_fixed/valid_1282/valid_128(…): reconstructing file:   0%|          |  0.00B /  113MB

dataset/valid_fixed/valid_1282/valid_128(…): downloading bytes:           |  0.00B

[43/200] valid_1282_a_2                       8.4s

dataset/valid_fixed/valid_1298/valid_129(…): reconstructing file:   0%|          |  0.00B / 98.2MB

dataset/valid_fixed/valid_1298/valid_129(…): downloading bytes:           |  0.00B

[44/200] valid_1298_a_1                       7.3s

dataset/valid_fixed/valid_129/valid_129_(…): reconstructing file:   0%|          |  0.00B /  181MB

dataset/valid_fixed/valid_129/valid_129_(…): downloading bytes:           |  0.00B

[45/200] valid_129_a_1                       11.2s

dataset/valid_fixed/valid_132/valid_132_(…): reconstructing file:   0%|          |  0.00B /  173MB

dataset/valid_fixed/valid_132/valid_132_(…): downloading bytes:           |  0.00B

[46/200] valid_132_a_2                        9.8s

dataset/valid_fixed/valid_13/valid_13_a/(…): reconstructing file:   0%|          |  0.00B /  134MB

dataset/valid_fixed/valid_13/valid_13_a/(…): downloading bytes:           |  0.00B

[47/200] valid_13_a_2                        25.2s

dataset/valid_fixed/valid_142/valid_142_(…): reconstructing file:   0%|          |  0.00B /  164MB

dataset/valid_fixed/valid_142/valid_142_(…): downloading bytes:           |  0.00B

[48/200] valid_142_a_1                        9.4s

dataset/valid_fixed/valid_145/valid_145_(…): reconstructing file:   0%|          |  0.00B / 68.1MB

dataset/valid_fixed/valid_145/valid_145_(…): downloading bytes:           |  0.00B

[49/200] valid_145_a_1                        6.9s

dataset/valid_fixed/valid_147/valid_147_(…): reconstructing file:   0%|          |  0.00B / 73.3MB

dataset/valid_fixed/valid_147/valid_147_(…): downloading bytes:           |  0.00B

[50/200] valid_147_a_2                        6.7s

dataset/valid_fixed/valid_156/valid_156_(…): reconstructing file:   0%|          |  0.00B /  113MB

dataset/valid_fixed/valid_156/valid_156_(…): downloading bytes:           |  0.00B

[51/200] valid_156_a_2                       10.4s

dataset/valid_fixed/valid_166/valid_166_(…): reconstructing file:   0%|          |  0.00B / 98.4MB

dataset/valid_fixed/valid_166/valid_166_(…): downloading bytes:           |  0.00B

[52/200] valid_166_a_2                        7.7s

dataset/valid_fixed/valid_182/valid_182_(…): reconstructing file:   0%|          |  0.00B /  148MB

dataset/valid_fixed/valid_182/valid_182_(…): downloading bytes:           |  0.00B

[53/200] valid_182_a_2                        9.9s

dataset/valid_fixed/valid_186/valid_186_(…): reconstructing file:   0%|          |  0.00B /  141MB

dataset/valid_fixed/valid_186/valid_186_(…): downloading bytes:           |  0.00B

[54/200] valid_186_a_2                       11.3s

dataset/valid_fixed/valid_190/valid_190_(…): reconstructing file:   0%|          |  0.00B / 69.7MB

dataset/valid_fixed/valid_190/valid_190_(…): downloading bytes:           |  0.00B

[55/200] valid_190_a_1                        8.4s

dataset/valid_fixed/valid_213/valid_213_(…): reconstructing file:   0%|          |  0.00B /  103MB

dataset/valid_fixed/valid_213/valid_213_(…): downloading bytes:           |  0.00B

[56/200] valid_213_a_1                       10.1s

dataset/valid_fixed/valid_215/valid_215_(…): reconstructing file:   0%|          |  0.00B / 63.3MB

dataset/valid_fixed/valid_215/valid_215_(…): downloading bytes:           |  0.00B

[57/200] valid_215_c_2                        6.0s

dataset/valid_fixed/valid_21/valid_21_a/(…): reconstructing file:   0%|          |  0.00B / 73.8MB

dataset/valid_fixed/valid_21/valid_21_a/(…): downloading bytes:           |  0.00B

[58/200] valid_21_a_1                         6.7s

dataset/valid_fixed/valid_228/valid_228_(…): reconstructing file:   0%|          |  0.00B /  206MB

dataset/valid_fixed/valid_228/valid_228_(…): downloading bytes:           |  0.00B

[59/200] valid_228_a_1                        9.0s

dataset/valid_fixed/valid_244/valid_244_(…): reconstructing file:   0%|          |  0.00B / 60.0MB

dataset/valid_fixed/valid_244/valid_244_(…): downloading bytes:           |  0.00B

[60/200] valid_244_a_1                        6.2s

dataset/valid_fixed/valid_250/valid_250_(…): reconstructing file:   0%|          |  0.00B /  111MB

dataset/valid_fixed/valid_250/valid_250_(…): downloading bytes:           |  0.00B

[61/200] valid_250_e_1                        8.9s

dataset/valid_fixed/valid_254/valid_254_(…): reconstructing file:   0%|          |  0.00B / 36.3MB

dataset/valid_fixed/valid_254/valid_254_(…): downloading bytes:           |  0.00B

[62/200] valid_254_a_2                        6.1s

dataset/valid_fixed/valid_264/valid_264_(…): reconstructing file:   0%|          |  0.00B /  130MB

dataset/valid_fixed/valid_264/valid_264_(…): downloading bytes:           |  0.00B

[63/200] valid_264_a_2                        9.2s

dataset/valid_fixed/valid_266/valid_266_(…): reconstructing file:   0%|          |  0.00B / 48.4MB

dataset/valid_fixed/valid_266/valid_266_(…): downloading bytes:           |  0.00B

[64/200] valid_266_a_1                        8.3s

dataset/valid_fixed/valid_276/valid_276_(…): reconstructing file:   0%|          |  0.00B / 58.1MB

dataset/valid_fixed/valid_276/valid_276_(…): downloading bytes:           |  0.00B

[65/200] valid_276_a_2                        7.2s

dataset/valid_fixed/valid_285/valid_285_(…): reconstructing file:   0%|          |  0.00B / 88.4MB

dataset/valid_fixed/valid_285/valid_285_(…): downloading bytes:           |  0.00B

[66/200] valid_285_a_1                        9.0s

dataset/valid_fixed/valid_291/valid_291_(…): reconstructing file:   0%|          |  0.00B /  135MB

dataset/valid_fixed/valid_291/valid_291_(…): downloading bytes:           |  0.00B

[67/200] valid_291_a_2                        8.7s

dataset/valid_fixed/valid_292/valid_292_(…): reconstructing file:   0%|          |  0.00B /  166MB

dataset/valid_fixed/valid_292/valid_292_(…): downloading bytes:           |  0.00B

[68/200] valid_292_a_1                        8.9s

dataset/valid_fixed/valid_2/valid_2_a/va(…): reconstructing file:   0%|          |  0.00B / 74.5MB

dataset/valid_fixed/valid_2/valid_2_a/va(…): downloading bytes:           |  0.00B

[69/200] valid_2_a_1                          7.1s

dataset/valid_fixed/valid_302/valid_302_(…): reconstructing file:   0%|          |  0.00B /  107MB

dataset/valid_fixed/valid_302/valid_302_(…): downloading bytes:           |  0.00B

[70/200] valid_302_a_1                        9.0s

dataset/valid_fixed/valid_303/valid_303_(…): reconstructing file:   0%|          |  0.00B /  117MB

dataset/valid_fixed/valid_303/valid_303_(…): downloading bytes:           |  0.00B

[71/200] valid_303_a_2                        7.8s

dataset/valid_fixed/valid_304/valid_304_(…): reconstructing file:   0%|          |  0.00B /  103MB

dataset/valid_fixed/valid_304/valid_304_(…): downloading bytes:           |  0.00B

[72/200] valid_304_a_1                       10.0s

dataset/valid_fixed/valid_311/valid_311_(…): reconstructing file:   0%|          |  0.00B / 56.7MB

dataset/valid_fixed/valid_311/valid_311_(…): downloading bytes:           |  0.00B

[73/200] valid_311_a_1                        6.8s

dataset/valid_fixed/valid_314/valid_314_(…): reconstructing file:   0%|          |  0.00B /  155MB

dataset/valid_fixed/valid_314/valid_314_(…): downloading bytes:           |  0.00B

[74/200] valid_314_a_2                        9.9s

dataset/valid_fixed/valid_322/valid_322_(…): reconstructing file:   0%|          |  0.00B / 87.6MB

dataset/valid_fixed/valid_322/valid_322_(…): downloading bytes:           |  0.00B

[75/200] valid_322_a_1                        9.6s

dataset/valid_fixed/valid_323/valid_323_(…): reconstructing file:   0%|          |  0.00B / 58.0MB

dataset/valid_fixed/valid_323/valid_323_(…): downloading bytes:           |  0.00B

[76/200] valid_323_a_1                        5.0s

dataset/valid_fixed/valid_32/valid_32_a/(…): reconstructing file:   0%|          |  0.00B /  178MB

dataset/valid_fixed/valid_32/valid_32_a/(…): downloading bytes:           |  0.00B

[77/200] valid_32_a_1                         8.8s

dataset/valid_fixed/valid_331/valid_331_(…): reconstructing file:   0%|          |  0.00B / 88.5MB

dataset/valid_fixed/valid_331/valid_331_(…): downloading bytes:           |  0.00B

[78/200] valid_331_e_2                       10.2s

dataset/valid_fixed/valid_332/valid_332_(…): reconstructing file:   0%|          |  0.00B / 66.9MB

dataset/valid_fixed/valid_332/valid_332_(…): downloading bytes:           |  0.00B

[79/200] valid_332_a_1                        7.7s

dataset/valid_fixed/valid_334/valid_334_(…): reconstructing file:   0%|          |  0.00B / 31.6MB

dataset/valid_fixed/valid_334/valid_334_(…): downloading bytes:           |  0.00B

[80/200] valid_334_a_2                       11.4s

dataset/valid_fixed/valid_335/valid_335_(…): reconstructing file:   0%|          |  0.00B / 71.4MB

dataset/valid_fixed/valid_335/valid_335_(…): downloading bytes:           |  0.00B

[81/200] valid_335_a_1                        6.8s

dataset/valid_fixed/valid_341/valid_341_(…): reconstructing file:   0%|          |  0.00B / 69.3MB

dataset/valid_fixed/valid_341/valid_341_(…): downloading bytes:           |  0.00B

[82/200] valid_341_a_1                        7.7s

dataset/valid_fixed/valid_348/valid_348_(…): reconstructing file:   0%|          |  0.00B / 69.3MB

dataset/valid_fixed/valid_348/valid_348_(…): downloading bytes:           |  0.00B

[83/200] valid_348_a_1                        9.1s

dataset/valid_fixed/valid_351/valid_351_(…): reconstructing file:   0%|          |  0.00B /  149MB

dataset/valid_fixed/valid_351/valid_351_(…): downloading bytes:           |  0.00B

[84/200] valid_351_b_2                       12.4s

dataset/valid_fixed/valid_357/valid_357_(…): reconstructing file:   0%|          |  0.00B /  131MB

dataset/valid_fixed/valid_357/valid_357_(…): downloading bytes:           |  0.00B

[85/200] valid_357_a_2                       11.9s

dataset/valid_fixed/valid_359/valid_359_(…): reconstructing file:   0%|          |  0.00B /  102MB

dataset/valid_fixed/valid_359/valid_359_(…): downloading bytes:           |  0.00B

[86/200] valid_359_a_1                        8.8s

dataset/valid_fixed/valid_35/valid_35_a/(…): reconstructing file:   0%|          |  0.00B / 61.3MB

dataset/valid_fixed/valid_35/valid_35_a/(…): downloading bytes:           |  0.00B

[87/200] valid_35_a_1                         5.2s

dataset/valid_fixed/valid_360/valid_360_(…): reconstructing file:   0%|          |  0.00B / 63.4MB

dataset/valid_fixed/valid_360/valid_360_(…): downloading bytes:           |  0.00B

[88/200] valid_360_a_2                        6.3s

dataset/valid_fixed/valid_373/valid_373_(…): reconstructing file:   0%|          |  0.00B /  107MB

dataset/valid_fixed/valid_373/valid_373_(…): downloading bytes:           |  0.00B

[89/200] valid_373_b_1                        8.0s

dataset/valid_fixed/valid_382/valid_382_(…): reconstructing file:   0%|          |  0.00B / 87.5MB

dataset/valid_fixed/valid_382/valid_382_(…): downloading bytes:           |  0.00B

[90/200] valid_382_c_1                        9.2s

dataset/valid_fixed/valid_402/valid_402_(…): reconstructing file:   0%|          |  0.00B /  188MB

dataset/valid_fixed/valid_402/valid_402_(…): downloading bytes:           |  0.00B

[91/200] valid_402_a_1                        9.9s

dataset/valid_fixed/valid_40/valid_40_a/(…): reconstructing file:   0%|          |  0.00B /  139MB

dataset/valid_fixed/valid_40/valid_40_a/(…): downloading bytes:           |  0.00B

[92/200] valid_40_a_2                        11.0s

dataset/valid_fixed/valid_410/valid_410_(…): reconstructing file:   0%|          |  0.00B / 68.5MB

dataset/valid_fixed/valid_410/valid_410_(…): downloading bytes:           |  0.00B

[93/200] valid_410_b_1                        7.4s

dataset/valid_fixed/valid_41/valid_41_b/(…): reconstructing file:   0%|          |  0.00B / 45.7MB

dataset/valid_fixed/valid_41/valid_41_b/(…): downloading bytes:           |  0.00B

[94/200] valid_41_b_2                         8.1s

dataset/valid_fixed/valid_424/valid_424_(…): reconstructing file:   0%|          |  0.00B /  108MB

dataset/valid_fixed/valid_424/valid_424_(…): downloading bytes:           |  0.00B

[95/200] valid_424_a_2                        8.5s

dataset/valid_fixed/valid_427/valid_427_(…): reconstructing file:   0%|          |  0.00B / 86.7MB

dataset/valid_fixed/valid_427/valid_427_(…): downloading bytes:           |  0.00B

[96/200] valid_427_a_1                        8.9s

dataset/valid_fixed/valid_429/valid_429_(…): reconstructing file:   0%|          |  0.00B / 59.4MB

dataset/valid_fixed/valid_429/valid_429_(…): downloading bytes:           |  0.00B

[97/200] valid_429_b_1                        6.3s

dataset/valid_fixed/valid_431/valid_431_(…): reconstructing file:   0%|          |  0.00B /  171MB

dataset/valid_fixed/valid_431/valid_431_(…): downloading bytes:           |  0.00B

[98/200] valid_431_a_1                        9.6s

dataset/valid_fixed/valid_434/valid_434_(…): reconstructing file:   0%|          |  0.00B /  167MB

dataset/valid_fixed/valid_434/valid_434_(…): downloading bytes:           |  0.00B

[99/200] valid_434_a_1                       10.5s

dataset/valid_fixed/valid_436/valid_436_(…): reconstructing file:   0%|          |  0.00B / 79.6MB

dataset/valid_fixed/valid_436/valid_436_(…): downloading bytes:           |  0.00B

[100/200] valid_436_a_2                        9.4s

dataset/valid_fixed/valid_442/valid_442_(…): reconstructing file:   0%|          |  0.00B /  131MB

dataset/valid_fixed/valid_442/valid_442_(…): downloading bytes:           |  0.00B

[101/200] valid_442_a_2                        9.4s

dataset/valid_fixed/valid_446/valid_446_(…): reconstructing file:   0%|          |  0.00B /  112MB

dataset/valid_fixed/valid_446/valid_446_(…): downloading bytes:           |  0.00B

[102/200] valid_446_b_2                        8.2s

dataset/valid_fixed/valid_449/valid_449_(…): reconstructing file:   0%|          |  0.00B / 66.7MB

dataset/valid_fixed/valid_449/valid_449_(…): downloading bytes:           |  0.00B

[103/200] valid_449_b_2                       14.5s

dataset/valid_fixed/valid_450/valid_450_(…): reconstructing file:   0%|          |  0.00B / 61.8MB

dataset/valid_fixed/valid_450/valid_450_(…): downloading bytes:           |  0.00B

[104/200] valid_450_a_1                        7.2s

dataset/valid_fixed/valid_459/valid_459_(…): reconstructing file:   0%|          |  0.00B / 59.5MB

dataset/valid_fixed/valid_459/valid_459_(…): downloading bytes:           |  0.00B

[105/200] valid_459_a_1                        8.0s

dataset/valid_fixed/valid_460/valid_460_(…): reconstructing file:   0%|          |  0.00B /  133MB

dataset/valid_fixed/valid_460/valid_460_(…): downloading bytes:           |  0.00B

[106/200] valid_460_a_2                        9.8s

dataset/valid_fixed/valid_461/valid_461_(…): reconstructing file:   0%|          |  0.00B / 65.3MB

dataset/valid_fixed/valid_461/valid_461_(…): downloading bytes:           |  0.00B

[107/200] valid_461_a_1                        7.5s

dataset/valid_fixed/valid_46/valid_46_a/(…): reconstructing file:   0%|          |  0.00B /  101MB

dataset/valid_fixed/valid_46/valid_46_a/(…): downloading bytes:           |  0.00B

[108/200] valid_46_a_1                         7.2s

dataset/valid_fixed/valid_476/valid_476_(…): reconstructing file:   0%|          |  0.00B /  107MB

dataset/valid_fixed/valid_476/valid_476_(…): downloading bytes:           |  0.00B

[109/200] valid_476_a_1                        9.6s

dataset/valid_fixed/valid_480/valid_480_(…): reconstructing file:   0%|          |  0.00B /  142MB

dataset/valid_fixed/valid_480/valid_480_(…): downloading bytes:           |  0.00B

[110/200] valid_480_a_2                       10.4s

dataset/valid_fixed/valid_485/valid_485_(…): reconstructing file:   0%|          |  0.00B /  122MB

dataset/valid_fixed/valid_485/valid_485_(…): downloading bytes:           |  0.00B

[111/200] valid_485_a_2                       10.2s

dataset/valid_fixed/valid_48/valid_48_a/(…): reconstructing file:   0%|          |  0.00B /  104MB

dataset/valid_fixed/valid_48/valid_48_a/(…): downloading bytes:           |  0.00B

[112/200] valid_48_a_1                         8.5s

dataset/valid_fixed/valid_492/valid_492_(…): reconstructing file:   0%|          |  0.00B / 96.7MB

dataset/valid_fixed/valid_492/valid_492_(…): downloading bytes:           |  0.00B

[113/200] valid_492_b_1                        8.4s

dataset/valid_fixed/valid_502/valid_502_(…): reconstructing file:   0%|          |  0.00B / 69.8MB

dataset/valid_fixed/valid_502/valid_502_(…): downloading bytes:           |  0.00B

[114/200] valid_502_a_1                        8.7s

dataset/valid_fixed/valid_508/valid_508_(…): reconstructing file:   0%|          |  0.00B / 56.9MB

dataset/valid_fixed/valid_508/valid_508_(…): downloading bytes:           |  0.00B

[115/200] valid_508_a_1                        6.2s

dataset/valid_fixed/valid_511/valid_511_(…): reconstructing file:   0%|          |  0.00B /  178MB

dataset/valid_fixed/valid_511/valid_511_(…): downloading bytes:           |  0.00B

[116/200] valid_511_a_1                       10.2s

dataset/valid_fixed/valid_512/valid_512_(…): reconstructing file:   0%|          |  0.00B /  110MB

dataset/valid_fixed/valid_512/valid_512_(…): downloading bytes:           |  0.00B

[117/200] valid_512_b_1                       10.9s

dataset/valid_fixed/valid_513/valid_513_(…): reconstructing file:   0%|          |  0.00B / 40.1MB

dataset/valid_fixed/valid_513/valid_513_(…): downloading bytes:           |  0.00B

[118/200] valid_513_a_2                        6.3s

dataset/valid_fixed/valid_516/valid_516_(…): reconstructing file:   0%|          |  0.00B /  167MB

dataset/valid_fixed/valid_516/valid_516_(…): downloading bytes:           |  0.00B

[119/200] valid_516_a_1                        8.5s

dataset/valid_fixed/valid_518/valid_518_(…): reconstructing file:   0%|          |  0.00B / 87.9MB

dataset/valid_fixed/valid_518/valid_518_(…): downloading bytes:           |  0.00B

[120/200] valid_518_a_2                        8.1s

dataset/valid_fixed/valid_522/valid_522_(…): reconstructing file:   0%|          |  0.00B /  178MB

dataset/valid_fixed/valid_522/valid_522_(…): downloading bytes:           |  0.00B

[121/200] valid_522_a_1                        9.4s

dataset/valid_fixed/valid_544/valid_544_(…): reconstructing file:   0%|          |  0.00B / 82.8MB

dataset/valid_fixed/valid_544/valid_544_(…): downloading bytes:           |  0.00B

[122/200] valid_544_a_1                        8.3s

dataset/valid_fixed/valid_546/valid_546_(…): reconstructing file:   0%|          |  0.00B /  143MB

dataset/valid_fixed/valid_546/valid_546_(…): downloading bytes:           |  0.00B

[123/200] valid_546_a_2                       11.4s

dataset/valid_fixed/valid_553/valid_553_(…): reconstructing file:   0%|          |  0.00B / 71.9MB

dataset/valid_fixed/valid_553/valid_553_(…): downloading bytes:           |  0.00B

[124/200] valid_553_a_1                        7.2s

dataset/valid_fixed/valid_567/valid_567_(…): reconstructing file:   0%|          |  0.00B / 91.8MB

dataset/valid_fixed/valid_567/valid_567_(…): downloading bytes:           |  0.00B

[125/200] valid_567_a_1                        8.7s

dataset/valid_fixed/valid_574/valid_574_(…): reconstructing file:   0%|          |  0.00B /  171MB

dataset/valid_fixed/valid_574/valid_574_(…): downloading bytes:           |  0.00B

[126/200] valid_574_a_1                       10.3s

dataset/valid_fixed/valid_583/valid_583_(…): reconstructing file:   0%|          |  0.00B /  148MB

dataset/valid_fixed/valid_583/valid_583_(…): downloading bytes:           |  0.00B

[127/200] valid_583_a_2                        9.1s

dataset/valid_fixed/valid_584/valid_584_(…): reconstructing file:   0%|          |  0.00B /  116MB

dataset/valid_fixed/valid_584/valid_584_(…): downloading bytes:           |  0.00B

[128/200] valid_584_a_2                        8.1s

dataset/valid_fixed/valid_594/valid_594_(…): reconstructing file:   0%|          |  0.00B /  191MB

dataset/valid_fixed/valid_594/valid_594_(…): downloading bytes:           |  0.00B

[129/200] valid_594_a_1                       11.0s

dataset/valid_fixed/valid_602/valid_602_(…): reconstructing file:   0%|          |  0.00B / 63.9MB

dataset/valid_fixed/valid_602/valid_602_(…): downloading bytes:           |  0.00B

[130/200] valid_602_a_1                        7.4s

dataset/valid_fixed/valid_605/valid_605_(…): reconstructing file:   0%|          |  0.00B /  146MB

dataset/valid_fixed/valid_605/valid_605_(…): downloading bytes:           |  0.00B

[131/200] valid_605_a_2                        8.6s

dataset/valid_fixed/valid_60/valid_60_b/(…): reconstructing file:   0%|          |  0.00B / 65.6MB

dataset/valid_fixed/valid_60/valid_60_b/(…): downloading bytes:           |  0.00B

[132/200] valid_60_b_2                         7.6s

dataset/valid_fixed/valid_610/valid_610_(…): reconstructing file:   0%|          |  0.00B /  102MB

dataset/valid_fixed/valid_610/valid_610_(…): downloading bytes:           |  0.00B

[133/200] valid_610_a_2                        8.4s

dataset/valid_fixed/valid_615/valid_615_(…): reconstructing file:   0%|          |  0.00B /  132MB

dataset/valid_fixed/valid_615/valid_615_(…): downloading bytes:           |  0.00B

[134/200] valid_615_a_2                       10.0s

dataset/valid_fixed/valid_617/valid_617_(…): reconstructing file:   0%|          |  0.00B /  108MB

dataset/valid_fixed/valid_617/valid_617_(…): downloading bytes:           |  0.00B

[135/200] valid_617_a_1                        9.2s

dataset/valid_fixed/valid_619/valid_619_(…): reconstructing file:   0%|          |  0.00B / 97.7MB

dataset/valid_fixed/valid_619/valid_619_(…): downloading bytes:           |  0.00B

[136/200] valid_619_a_2                        9.3s

dataset/valid_fixed/valid_622/valid_622_(…): reconstructing file:   0%|          |  0.00B / 43.2MB

dataset/valid_fixed/valid_622/valid_622_(…): downloading bytes:           |  0.00B

[137/200] valid_622_a_2                        5.9s

dataset/valid_fixed/valid_624/valid_624_(…): reconstructing file:   0%|          |  0.00B / 61.6MB

dataset/valid_fixed/valid_624/valid_624_(…): downloading bytes:           |  0.00B

[138/200] valid_624_b_1                        8.7s

dataset/valid_fixed/valid_632/valid_632_(…): reconstructing file:   0%|          |  0.00B /  176MB

dataset/valid_fixed/valid_632/valid_632_(…): downloading bytes:           |  0.00B

[139/200] valid_632_a_1                       10.2s

dataset/valid_fixed/valid_647/valid_647_(…): reconstructing file:   0%|          |  0.00B / 93.8MB

dataset/valid_fixed/valid_647/valid_647_(…): downloading bytes:           |  0.00B

[140/200] valid_647_a_2                        7.2s

dataset/valid_fixed/valid_64/valid_64_b/(…): reconstructing file:   0%|          |  0.00B / 66.0MB

dataset/valid_fixed/valid_64/valid_64_b/(…): downloading bytes:           |  0.00B

[141/200] valid_64_b_2                         6.4s

dataset/valid_fixed/valid_651/valid_651_(…): reconstructing file:   0%|          |  0.00B / 58.0MB

dataset/valid_fixed/valid_651/valid_651_(…): downloading bytes:           |  0.00B

[142/200] valid_651_a_1                        4.9s

dataset/valid_fixed/valid_653/valid_653_(…): reconstructing file:   0%|          |  0.00B /  100MB

dataset/valid_fixed/valid_653/valid_653_(…): downloading bytes:           |  0.00B

[143/200] valid_653_a_1                        8.5s

dataset/valid_fixed/valid_658/valid_658_(…): reconstructing file:   0%|          |  0.00B / 85.7MB

dataset/valid_fixed/valid_658/valid_658_(…): downloading bytes:           |  0.00B

[144/200] valid_658_a_1                        7.9s

dataset/valid_fixed/valid_661/valid_661_(…): reconstructing file:   0%|          |  0.00B / 70.7MB

dataset/valid_fixed/valid_661/valid_661_(…): downloading bytes:           |  0.00B

[145/200] valid_661_a_1                        8.4s

dataset/valid_fixed/valid_662/valid_662_(…): reconstructing file:   0%|          |  0.00B / 78.9MB

dataset/valid_fixed/valid_662/valid_662_(…): downloading bytes:           |  0.00B

[146/200] valid_662_a_1                        8.8s

dataset/valid_fixed/valid_668/valid_668_(…): reconstructing file:   0%|          |  0.00B / 57.1MB

dataset/valid_fixed/valid_668/valid_668_(…): downloading bytes:           |  0.00B

[147/200] valid_668_b_2                        5.3s

dataset/valid_fixed/valid_66/valid_66_a/(…): reconstructing file:   0%|          |  0.00B /  172MB

dataset/valid_fixed/valid_66/valid_66_a/(…): downloading bytes:           |  0.00B

[148/200] valid_66_a_1                        10.7s

dataset/valid_fixed/valid_670/valid_670_(…): reconstructing file:   0%|          |  0.00B /  154MB

dataset/valid_fixed/valid_670/valid_670_(…): downloading bytes:           |  0.00B

[149/200] valid_670_a_2                       11.8s

dataset/valid_fixed/valid_676/valid_676_(…): reconstructing file:   0%|          |  0.00B / 73.2MB

dataset/valid_fixed/valid_676/valid_676_(…): downloading bytes:           |  0.00B

[150/200] valid_676_a_1                        7.0s

dataset/valid_fixed/valid_682/valid_682_(…): reconstructing file:   0%|          |  0.00B /  116MB

dataset/valid_fixed/valid_682/valid_682_(…): downloading bytes:           |  0.00B

[151/200] valid_682_a_2                        7.8s

dataset/valid_fixed/valid_685/valid_685_(…): reconstructing file:   0%|          |  0.00B /  122MB

dataset/valid_fixed/valid_685/valid_685_(…): downloading bytes:           |  0.00B

[152/200] valid_685_a_2                       11.5s

dataset/valid_fixed/valid_696/valid_696_(…): reconstructing file:   0%|          |  0.00B / 60.4MB

dataset/valid_fixed/valid_696/valid_696_(…): downloading bytes:           |  0.00B

[153/200] valid_696_a_1                        6.5s

dataset/valid_fixed/valid_714/valid_714_(…): reconstructing file:   0%|          |  0.00B /  181MB

dataset/valid_fixed/valid_714/valid_714_(…): downloading bytes:           |  0.00B

[154/200] valid_714_a_1                        8.6s

dataset/valid_fixed/valid_732/valid_732_(…): reconstructing file:   0%|          |  0.00B / 81.7MB

dataset/valid_fixed/valid_732/valid_732_(…): downloading bytes:           |  0.00B

[155/200] valid_732_a_1                        6.2s

dataset/valid_fixed/valid_736/valid_736_(…): reconstructing file:   0%|          |  0.00B / 72.1MB

dataset/valid_fixed/valid_736/valid_736_(…): downloading bytes:           |  0.00B

[156/200] valid_736_a_2                        6.3s

dataset/valid_fixed/valid_754/valid_754_(…): reconstructing file:   0%|          |  0.00B / 49.7MB

dataset/valid_fixed/valid_754/valid_754_(…): downloading bytes:           |  0.00B

[157/200] valid_754_a_2                        9.1s

dataset/valid_fixed/valid_768/valid_768_(…): reconstructing file:   0%|          |  0.00B /  163MB

dataset/valid_fixed/valid_768/valid_768_(…): downloading bytes:           |  0.00B

[158/200] valid_768_a_2                       11.7s

dataset/valid_fixed/valid_771/valid_771_(…): reconstructing file:   0%|          |  0.00B /  116MB

dataset/valid_fixed/valid_771/valid_771_(…): downloading bytes:           |  0.00B

[159/200] valid_771_b_2                        9.1s

dataset/valid_fixed/valid_776/valid_776_(…): reconstructing file:   0%|          |  0.00B / 59.9MB

dataset/valid_fixed/valid_776/valid_776_(…): downloading bytes:           |  0.00B

[160/200] valid_776_a_1                        6.9s

dataset/valid_fixed/valid_777/valid_777_(…): reconstructing file:   0%|          |  0.00B / 68.6MB

dataset/valid_fixed/valid_777/valid_777_(…): downloading bytes:           |  0.00B

[161/200] valid_777_a_1                        7.7s

dataset/valid_fixed/valid_778/valid_778_(…): reconstructing file:   0%|          |  0.00B / 65.5MB

dataset/valid_fixed/valid_778/valid_778_(…): downloading bytes:           |  0.00B

[162/200] valid_778_b_1                        7.3s

dataset/valid_fixed/valid_784/valid_784_(…): reconstructing file:   0%|          |  0.00B / 74.5MB

dataset/valid_fixed/valid_784/valid_784_(…): downloading bytes:           |  0.00B

[163/200] valid_784_a_2                        9.5s

dataset/valid_fixed/valid_790/valid_790_(…): reconstructing file:   0%|          |  0.00B / 65.5MB

dataset/valid_fixed/valid_790/valid_790_(…): downloading bytes:           |  0.00B

[164/200] valid_790_a_2                        6.9s

dataset/valid_fixed/valid_793/valid_793_(…): reconstructing file:   0%|          |  0.00B /  170MB

dataset/valid_fixed/valid_793/valid_793_(…): downloading bytes:           |  0.00B

[165/200] valid_793_a_1                        8.3s

dataset/valid_fixed/valid_804/valid_804_(…): reconstructing file:   0%|          |  0.00B /  107MB

dataset/valid_fixed/valid_804/valid_804_(…): downloading bytes:           |  0.00B

[166/200] valid_804_b_2                        7.6s

dataset/valid_fixed/valid_815/valid_815_(…): reconstructing file:   0%|          |  0.00B / 71.9MB

dataset/valid_fixed/valid_815/valid_815_(…): downloading bytes:           |  0.00B

[167/200] valid_815_c_1                       11.4s

dataset/valid_fixed/valid_817/valid_817_(…): reconstructing file:   0%|          |  0.00B / 74.4MB

dataset/valid_fixed/valid_817/valid_817_(…): downloading bytes:           |  0.00B

[168/200] valid_817_a_1                        8.2s

dataset/valid_fixed/valid_822/valid_822_(…): reconstructing file:   0%|          |  0.00B / 75.5MB

dataset/valid_fixed/valid_822/valid_822_(…): downloading bytes:           |  0.00B

[169/200] valid_822_a_2                        9.9s

dataset/valid_fixed/valid_827/valid_827_(…): reconstructing file:   0%|          |  0.00B / 60.2MB

dataset/valid_fixed/valid_827/valid_827_(…): downloading bytes:           |  0.00B

[170/200] valid_827_a_1                        5.4s

dataset/valid_fixed/valid_829/valid_829_(…): reconstructing file:   0%|          |  0.00B / 65.1MB

dataset/valid_fixed/valid_829/valid_829_(…): downloading bytes:           |  0.00B

[171/200] valid_829_a_2                        7.4s

dataset/valid_fixed/valid_82/valid_82_a/(…): reconstructing file:   0%|          |  0.00B / 64.0MB

dataset/valid_fixed/valid_82/valid_82_a/(…): downloading bytes:           |  0.00B

[172/200] valid_82_a_1                         5.8s

dataset/valid_fixed/valid_830/valid_830_(…): reconstructing file:   0%|          |  0.00B / 56.9MB

dataset/valid_fixed/valid_830/valid_830_(…): downloading bytes:           |  0.00B

[173/200] valid_830_c_2                        6.6s

dataset/valid_fixed/valid_836/valid_836_(…): reconstructing file:   0%|          |  0.00B /  117MB

dataset/valid_fixed/valid_836/valid_836_(…): downloading bytes:           |  0.00B

[174/200] valid_836_a_2                        8.6s

dataset/valid_fixed/valid_845/valid_845_(…): reconstructing file:   0%|          |  0.00B / 82.8MB

dataset/valid_fixed/valid_845/valid_845_(…): downloading bytes:           |  0.00B

[175/200] valid_845_a_1                        7.8s

dataset/valid_fixed/valid_866/valid_866_(…): reconstructing file:   0%|          |  0.00B /  144MB

dataset/valid_fixed/valid_866/valid_866_(…): downloading bytes:           |  0.00B

[176/200] valid_866_a_2                       11.8s

dataset/valid_fixed/valid_870/valid_870_(…): reconstructing file:   0%|          |  0.00B /  110MB

dataset/valid_fixed/valid_870/valid_870_(…): downloading bytes:           |  0.00B

[177/200] valid_870_a_1                        8.0s

dataset/valid_fixed/valid_872/valid_872_(…): reconstructing file:   0%|          |  0.00B / 90.4MB

dataset/valid_fixed/valid_872/valid_872_(…): downloading bytes:           |  0.00B

[178/200] valid_872_a_1                        6.8s

dataset/valid_fixed/valid_873/valid_873_(…): reconstructing file:   0%|          |  0.00B /  123MB

dataset/valid_fixed/valid_873/valid_873_(…): downloading bytes:           |  0.00B

[179/200] valid_873_a_2                       10.1s

dataset/valid_fixed/valid_878/valid_878_(…): reconstructing file:   0%|          |  0.00B /  110MB

dataset/valid_fixed/valid_878/valid_878_(…): downloading bytes:           |  0.00B

[180/200] valid_878_a_1                       11.1s

dataset/valid_fixed/valid_883/valid_883_(…): reconstructing file:   0%|          |  0.00B /  134MB

dataset/valid_fixed/valid_883/valid_883_(…): downloading bytes:           |  0.00B

[181/200] valid_883_a_2                       11.6s

dataset/valid_fixed/valid_887/valid_887_(…): reconstructing file:   0%|          |  0.00B / 88.2MB

dataset/valid_fixed/valid_887/valid_887_(…): downloading bytes:           |  0.00B

[182/200] valid_887_a_2                        8.9s

dataset/valid_fixed/valid_890/valid_890_(…): reconstructing file:   0%|          |  0.00B / 84.1MB

dataset/valid_fixed/valid_890/valid_890_(…): downloading bytes:           |  0.00B

[183/200] valid_890_a_2                        9.1s

dataset/valid_fixed/valid_898/valid_898_(…): reconstructing file:   0%|          |  0.00B / 63.5MB

dataset/valid_fixed/valid_898/valid_898_(…): downloading bytes:           |  0.00B

[184/200] valid_898_a_1                        7.9s

dataset/valid_fixed/valid_907/valid_907_(…): reconstructing file:   0%|          |  0.00B /  150MB

dataset/valid_fixed/valid_907/valid_907_(…): downloading bytes:           |  0.00B

[185/200] valid_907_a_1                        9.4s

dataset/valid_fixed/valid_911/valid_911_(…): reconstructing file:   0%|          |  0.00B /  146MB

dataset/valid_fixed/valid_911/valid_911_(…): downloading bytes:           |  0.00B

[186/200] valid_911_a_2                       10.5s

dataset/valid_fixed/valid_914/valid_914_(…): reconstructing file:   0%|          |  0.00B / 66.0MB

dataset/valid_fixed/valid_914/valid_914_(…): downloading bytes:           |  0.00B

[187/200] valid_914_a_2                        6.8s

dataset/valid_fixed/valid_921/valid_921_(…): reconstructing file:   0%|          |  0.00B / 80.4MB

dataset/valid_fixed/valid_921/valid_921_(…): downloading bytes:           |  0.00B

[188/200] valid_921_a_1                        8.5s

dataset/valid_fixed/valid_922/valid_922_(…): reconstructing file:   0%|          |  0.00B / 98.3MB

dataset/valid_fixed/valid_922/valid_922_(…): downloading bytes:           |  0.00B

[189/200] valid_922_a_1                        8.7s

dataset/valid_fixed/valid_930/valid_930_(…): reconstructing file:   0%|          |  0.00B / 98.3MB

dataset/valid_fixed/valid_930/valid_930_(…): downloading bytes:           |  0.00B

[190/200] valid_930_a_2                        9.4s

dataset/valid_fixed/valid_932/valid_932_(…): reconstructing file:   0%|          |  0.00B / 58.0MB

dataset/valid_fixed/valid_932/valid_932_(…): downloading bytes:           |  0.00B

[191/200] valid_932_a_1                        8.0s

dataset/valid_fixed/valid_938/valid_938_(…): reconstructing file:   0%|          |  0.00B /  163MB

dataset/valid_fixed/valid_938/valid_938_(…): downloading bytes:           |  0.00B

[192/200] valid_938_a_1                        9.1s

dataset/valid_fixed/valid_947/valid_947_(…): reconstructing file:   0%|          |  0.00B /  122MB

dataset/valid_fixed/valid_947/valid_947_(…): downloading bytes:           |  0.00B

[193/200] valid_947_a_2                        8.6s

dataset/valid_fixed/valid_957/valid_957_(…): reconstructing file:   0%|          |  0.00B /  130MB

dataset/valid_fixed/valid_957/valid_957_(…): downloading bytes:           |  0.00B

[194/200] valid_957_a_2                        7.9s

dataset/valid_fixed/valid_963/valid_963_(…): reconstructing file:   0%|          |  0.00B /  115MB

dataset/valid_fixed/valid_963/valid_963_(…): downloading bytes:           |  0.00B

[195/200] valid_963_a_2                        8.4s

dataset/valid_fixed/valid_965/valid_965_(…): reconstructing file:   0%|          |  0.00B /  138MB

dataset/valid_fixed/valid_965/valid_965_(…): downloading bytes:           |  0.00B

[196/200] valid_965_a_2                       12.6s

dataset/valid_fixed/valid_968/valid_968_(…): reconstructing file:   0%|          |  0.00B / 98.3MB

dataset/valid_fixed/valid_968/valid_968_(…): downloading bytes:           |  0.00B

[197/200] valid_968_d_1                        9.1s

dataset/valid_fixed/valid_974/valid_974_(…): reconstructing file:   0%|          |  0.00B / 69.8MB

dataset/valid_fixed/valid_974/valid_974_(…): downloading bytes:           |  0.00B

[198/200] valid_974_a_1                        8.5s

dataset/valid_fixed/valid_977/valid_977_(…): reconstructing file:   0%|          |  0.00B /  121MB

dataset/valid_fixed/valid_977/valid_977_(…): downloading bytes:           |  0.00B

[199/200] valid_977_a_2                        9.4s

dataset/valid_fixed/valid_985/valid_985_(…): reconstructing file:   0%|          |  0.00B / 63.7MB

dataset/valid_fixed/valid_985/valid_985_(…): downloading bytes:           |  0.00B

[200/200] valid_985_a_1                        6.5s
done in 29.7 min | failed: 0

In [9]:
# ---- assemble tables from the cache
rows, EMB = [], {k: {} for k in KEYS_NEEDED}
for it in ITEMS:
    c = load_cache(it)
    if not c or "meta" not in c or any(k not in c for k in KEYS_NEEDED):
        continue
    meta = json.loads(str(c["meta"]))
    rows.append(dict(id=it["id"], cohort=it["cohort"], group=it["group"], name=it.get("name"), vendor=vendor_group(meta.get("vendor")), kernel=kernel_family(meta.get("kernel"))))
    for k in EMB:
        EMB[k][it["id"]] = c[k]
META_DF = pd.DataFrame(rows).set_index("id") if rows else pd.DataFrame(columns=["cohort", "group", "name", "vendor", "kernel"], index=pd.Index([], name="id"))
POS = {i: n for n, i in enumerate(META_DF.index)}
EMB = {k: np.vstack([v[i] for i in META_DF.index]) for k, v in EMB.items() if v}
print("scans with complete features:", len(META_DF))
if len(META_DF):
    display(pd.crosstab(META_DF.vendor, META_DF.kernel, margins=True))

scans with complete features: 200

kernel    A   B  Bl56f  Bl57d  Br36d  Br40f  Br44f  Br60f  EA  L  SA  SB  All
vendor
PNMS      0   0      0      0      0      0      0      0  23  0   9   1   33
Philips  23  24      0      0      0      0      0      0   0  1   0   0   48
Siemens   0   0     23     23     23     23      4     23   0  0   0   0  119
All      23  24     23     23     23     23      4     23  23  1   9   1  200

## 7. Statistics helpers
Only what the paired comparison in sections 8-9 needs (no domain-gap / novelty toolbox here). `bh_fdr` is reused verbatim from `CT_Domain_Gap_Analysis.ipynb`; `paired_bootstrap_ci` is a small addition in the same style, for a paired (not independent-sample) bootstrap.

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GroupKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score
from scipy.stats import wilcoxon
from itertools import combinations

RNG = np.random.default_rng(12345)

def bh_fdr(p):
    p = np.asarray(p, float); n = len(p); o = np.argsort(p); q = np.empty(n); prev = 1.0
    for rank, i in zip(range(n, 0, -1), o[::-1]):
        prev = min(prev, p[i] * n / rank); q[i] = prev
    return q

def paired_bootstrap_ci(diffs, n_boot, rng):
    """Bootstrap CI on the MEAN of an already-paired difference vector (e.g. per-label AUROC_a - AUROC_b)."""
    diffs = diffs[~np.isnan(diffs)]
    if len(diffs) == 0:
        return (np.nan, np.nan)
    vals = [np.mean(rng.choice(diffs, len(diffs), replace=True)) for _ in range(n_boot)]
    return tuple(np.nanpercentile(vals, [2.5, 97.5]))

## 8. Linear-probe / kNN-probe evaluation on CT-RATE labels (primary, and only, evidence)
For every one of the 9 methods: a cross-validated logistic-regression probe (macro AUROC across the 18 labels) and a k-NN probe (training-free complement, the standard self-supervised-evaluation protocol). The **same** `GroupKFold` splits (grouped by patient) are reused for every method and every label, so the comparison across methods is paired. A label is only probed if it has at least `MIN_POS` positives and `MIN_POS` negatives in the whole labelled set.

In [11]:
def build_label_matrix(meta_df, ct_labels, items):
    names = {it["id"]: it.get("name") for it in items}
    ids = [i for i in meta_df.index if names.get(i) in ct_labels.index]
    Y = ct_labels.loc[[names[i] for i in ids], PATHOLOGIES].to_numpy(float)
    groups = meta_df.loc[ids, "group"].to_numpy()
    return ids, Y, groups

def linear_probe_auroc(X, Y, folds, min_pos=MIN_POS):
    aurocs = np.full(Y.shape[1], np.nan)
    for j in range(Y.shape[1]):
        y = Y[:, j]
        if y.sum() < min_pos or (len(y) - y.sum()) < min_pos:
            continue
        preds = np.full(len(y), np.nan); ok = True
        for tr, te in folds:
            if len(np.unique(y[tr])) < 2:
                ok = False; break
            sc = StandardScaler().fit(X[tr])
            clf = LogisticRegression(C=1.0, class_weight="balanced", max_iter=2000).fit(sc.transform(X[tr]), y[tr])
            preds[te] = clf.decision_function(sc.transform(X[te]))
        if ok:
            try:
                aurocs[j] = roc_auc_score(y, preds)
            except Exception:
                pass
    return aurocs

def knn_probe_auroc(X, Y, folds, k=15, min_pos=MIN_POS):
    aurocs = np.full(Y.shape[1], np.nan)
    for j in range(Y.shape[1]):
        y = Y[:, j]
        if y.sum() < min_pos or (len(y) - y.sum()) < min_pos:
            continue
        preds = np.full(len(y), np.nan)
        for tr, te in folds:
            sc = StandardScaler().fit(X[tr])
            clf = KNeighborsClassifier(n_neighbors=min(k, len(tr) - 1), weights="distance").fit(sc.transform(X[tr]), y[tr])
            p = clf.predict_proba(sc.transform(X[te]))
            preds[te] = p[:, list(clf.classes_).index(1)] if 1 in clf.classes_ else 0.0
        try:
            aurocs[j] = roc_auc_score(y, preds)
        except Exception:
            pass
    return aurocs

RESULTS, PER_LABEL_AUC = [], {}
if CT_META is not None and len(EMB):
    PROBE_IDS, Y, GROUPS_P = build_label_matrix(META_DF, ct_labels, ITEMS)
    print(f"probe set: {len(PROBE_IDS)} CT-RATE scans with labels | {Y.shape[1]} candidate labels")
    if len(PROBE_IDS) >= 20:
        folds = list(GroupKFold(n_splits=PROBE_FOLDS).split(np.zeros(len(PROBE_IDS)), groups=GROUPS_P))
        rows_idx = [POS[i] for i in PROBE_IDS]
        for key, Xfull in EMB.items():
            X = Xfull[rows_idx]
            auc_lin = linear_probe_auroc(X, Y, folds)
            auc_knn = knn_probe_auroc(X, Y, folds)
            PER_LABEL_AUC[key] = auc_lin
            RESULTS.append(dict(key=key, space=SPACE_OF[key], macro_auroc_linear=float(np.nanmean(auc_lin)), macro_auroc_knn=float(np.nanmean(auc_knn)), n_labels_evaluated=int(np.sum(~np.isnan(auc_lin)))))
        RES_DF = pd.DataFrame(RESULTS).sort_values("macro_auroc_linear", ascending=False)
        display(Markdown("#### Macro AUROC across the 18 CT-RATE labels - how well does each method's frozen features recognise abnormality patterns?"))
        display(RES_DF.round(3))
        RES_DF.round(4).to_csv(OUTPUT_DIR / "probe_results.csv", index=False)
        LABEL_AUC_DF = pd.DataFrame(PER_LABEL_AUC, index=PATHOLOGIES)
        LABEL_AUC_DF.round(4).to_csv(OUTPUT_DIR / "per_label_auroc.csv")
        display(Markdown("#### Per-label AUROC (linear probe), methods as columns"))
        display(LABEL_AUC_DF.round(3))
    else:
        print("too few labelled CT-RATE scans for the probes (need >= 20) - increase N_CTRATE")
else:
    print("probe evaluation skipped (CT-RATE labels unavailable)")

probe set: 200 CT-RATE scans with labels | 18 candidate labels

#### Macro AUROC across the 18 CT-RATE labels - how well does each method's frozen features recognise abnormality patterns?

,key,space,macro_auroc_linear,macro_auroc_knn,n_labels_evaluated
2,dino2_adjacent,DINOv2-S / adjacent,0.675,0.625,18
1,dino2_windows,DINOv2-S / windows,0.674,0.616,18
0,dino2_same,DINOv2-S / same,0.673,0.618,18
6,dino3_adjacent,DINOv3-S / adjacent,0.665,0.602,18
7,dino3_window_edge,DINOv3-S / window_edge,0.663,0.600,18
8,dale,"DALE-CT-0 (1-channel, native)",0.663,0.611,18
5,dino3_windows,DINOv3-S / windows,0.648,0.607,18
4,dino3_same,DINOv3-S / same,0.647,0.604,18
3,dino2_window_edge,DINOv2-S / window_edge,0.639,0.596,18

#### Per-label AUROC (linear probe), methods as columns

,dino2_same,dino2_windows,dino2_adjacent,dino2_window_edge,dino3_same,dino3_windows,dino3_adjacent,dino3_window_edge,dale
Medical material,0.820,0.767,0.815,0.794,0.803,0.807,0.817,0.805,0.841
Arterial wall calcification,0.788,0.810,0.840,0.781,0.764,0.749,0.760,0.728,0.752
Cardiomegaly,0.785,0.774,0.802,0.716,0.763,0.774,0.754,0.798,0.815
Pericardial effusion,0.544,0.652,0.578,0.590,0.356,0.435,0.468,0.447,0.590
Coronary artery wall calcification,0.801,0.852,0.849,0.834,0.780,0.775,0.825,0.772,0.751
Hiatal hernia,0.575,0.631,0.555,0.560,0.507,0.475,0.528,0.621,0.649
Lymphadenopathy,0.463,0.501,0.537,0.493,0.565,0.559,0.568,0.625,0.586
Emphysema,0.688,0.562,0.690,0.607,0.617,0.691,0.638,0.609,0.614
Atelectasis,0.608,0.708,0.668,0.635,0.615,0.620,0.616,0.632,0.647
Lung nodule,0.503,0.531,0.538,0.428,0.552,0.535,0.515,0.562,0.556
Lung opacity,0.655,0.623,0.591,0.591,0.552,0.506,0.604,0.585,0.505
Pulmonary fibrotic sequela,0.734,0.662,0.673,0.645,0.585,0.634,0.586,0.618,0.577
Pleural effusion,0.874,0.935,0.876,0.886,0.849,0.898,0.888,0.877,0.885
Mosaic attenuation pattern,0.714,0.799,0.823,0.748,0.754,0.791,0.739,0.748,0.839
Peribronchial thickening,0.567,0.496,0.499,0.485,0.636,0.626,0.710,0.600,0.674
Consolidation,0.654,0.629,0.637,0.571,0.626,0.587,0.631,0.591,0.584
Bronchiectasis,0.577,0.449,0.453,0.434,0.529,0.509,0.530,0.600,0.409
Interlobular septal thickening,0.764,0.753,0.731,0.698,0.786,0.694,0.785,0.724,0.654

## 9. Pairwise comparison across all 9 methods
For every pair of methods: the mean per-label AUROC difference with a paired bootstrap CI, a Wilcoxon signed-rank test across the 18 labels, and Benjamini-Hochberg correction across all pairwise comparisons together.

In [12]:
PAIR_ROWS = []
if len(PER_LABEL_AUC) >= 2:
    for a, b in combinations(PER_LABEL_AUC, 2):
        va, vb = PER_LABEL_AUC[a], PER_LABEL_AUC[b]
        mask = ~np.isnan(va) & ~np.isnan(vb)
        if mask.sum() < 5:
            continue
        diff = va[mask] - vb[mask]
        lo, hi = paired_bootstrap_ci(diff, N_BOOT, RNG)
        try:
            _, p = wilcoxon(va[mask], vb[mask])
        except Exception:
            p = np.nan
        PAIR_ROWS.append(dict(a=a, b=b, mean_auroc_diff=float(np.mean(diff)), ci_lo=lo, ci_hi=hi, n_labels=int(mask.sum()), wilcoxon_p=p))
    PAIR_DF = pd.DataFrame(PAIR_ROWS)
    if len(PAIR_DF):
        PAIR_DF["p_fdr"] = bh_fdr(PAIR_DF.wilcoxon_p.fillna(1.0).to_numpy())
        display(Markdown("#### Pairwise comparisons across all 9 methods (positive diff = `a` beats `b`; sorted by effect size)"))
        display(PAIR_DF.sort_values("mean_auroc_diff", key=lambda s: -s.abs()).round(4))
        PAIR_DF.round(4).to_csv(OUTPUT_DIR / "method_pairwise_stats.csv", index=False)
else:
    PAIR_DF = pd.DataFrame()
    print("pairwise comparison skipped (need probe results from section 8)")

#### Pairwise comparisons across all 9 methods (positive diff = `a` beats `b`; sorted by effect size)

,a,b,mean_auroc_diff,ci_lo,ci_hi,n_labels,wilcoxon_p,p_fdr
15,dino2_adjacent,dino2_window_edge,0.0365,0.0206,0.0529,18,0.0003,0.0118
9,dino2_windows,dino2_window_edge,0.0353,0.0187,0.0511,18,0.0010,0.0188
2,dino2_same,dino2_window_edge,0.0343,0.0083,0.0602,18,0.0342,0.3476
16,dino2_adjacent,dino3_same,0.0285,-0.0044,0.0628,18,0.1297,0.6329
10,dino2_windows,dino3_same,0.0273,-0.0151,0.0749,18,0.2645,0.6329
17,dino2_adjacent,dino3_windows,0.0272,-0.0024,0.0542,18,0.0432,0.3476
3,dino2_same,dino3_same,0.0263,-0.0048,0.0604,18,0.1674,0.6329
11,dino2_windows,dino3_windows,0.0260,-0.0146,0.0658,18,0.2462,0.6329
23,dino2_window_edge,dino3_adjacent,-0.0259,-0.0585,0.0062,18,0.1540,0.6329
4,dino2_same,dino3_windows,0.0249,-0.0044,0.0554,18,0.1540,0.6329
24,dino2_window_edge,dino3_window_edge,-0.0247,-0.0605,0.0101,18,0.2837,0.6329
25,dino2_window_edge,dale,-0.0238,-0.0592,0.0103,18,0.1930,0.6329
27,dino3_same,dino3_adjacent,-0.0179,-0.0347,-0.0032,18,0.0483,0.3476
28,dino3_same,dino3_window_edge,-0.0168,-0.0390,0.0043,18,0.2645,0.6329
30,dino3_windows,dino3_adjacent,-0.0165,-0.0386,0.0045,18,0.2121,0.6329
29,dino3_same,dale,-0.0159,-0.0544,0.0226,18,0.4951,0.7426
31,dino3_windows,dino3_window_edge,-0.0154,-0.0400,0.0078,18,0.3465,0.6329
32,dino3_windows,dale,-0.0145,-0.0475,0.0157,18,0.4951,0.7426
20,dino2_adjacent,dale,0.0127,-0.0185,0.0439,18,0.3692,0.6329
19,dino2_adjacent,dino3_window_edge,0.0118,-0.0229,0.0443,18,0.3692,0.6329
14,dino2_windows,dale,0.0115,-0.0261,0.0457,18,0.3692,0.6329
18,dino2_adjacent,dino3_adjacent,0.0106,-0.0237,0.0421,18,0.2645,0.6329
13,dino2_windows,dino3_window_edge,0.0106,-0.0286,0.0474,18,0.5226,0.7455
7,dino2_same,dale,0.0104,-0.0306,0.0512,18,0.7337,0.9108
6,dino2_same,dino3_window_edge,0.0096,-0.0226,0.0387,18,0.4171,0.6826
12,dino2_windows,dino3_adjacent,0.0094,-0.0327,0.0484,18,0.5798,0.7455
22,dino2_window_edge,dino3_windows,-0.0093,-0.0421,0.0230,18,0.5798,0.7455
5,dino2_same,dino3_adjacent,0.0084,-0.0217,0.0363,18,0.3247,0.6329
21,dino2_window_edge,dino3_same,-0.0080,-0.0464,0.0341,18,0.5509,0.7455
1,dino2_same,dino2_adjacent,-0.0022,-0.0287,0.0268,18,0.8650,0.9323
34,dino3_adjacent,dale,0.0020,-0.0315,0.0379,18,0.8986,0.9323
26,dino3_same,dino3_windows,-0.0014,-0.0204,0.0169,18,0.9323,0.9323
8,dino2_windows,dino2_adjacent,-0.0012,-0.0226,0.0201,18,0.8317,0.9323
33,dino3_adjacent,dino3_window_edge,0.0012,-0.0210,0.0252,18,0.9323,0.9323
0,dino2_same,dino2_windows,-0.0010,-0.0330,0.0320,18,0.8986,0.9323
35,dino3_window_edge,dale,0.0009,-0.0304,0.0347,18,0.8650,0.9323

## 10. Summary

In [13]:
SUMMARY = {"n_ctrate": len(META_DF) if len(META_DF) else 0, "device": DEV, "dry_run": DRY_RUN_RANDOM_WEIGHTS, "created": dt.datetime.now().isoformat(timespec="seconds")}
lines = []
if RESULTS:
    best = pd.DataFrame(RESULTS).sort_values("macro_auroc_linear", ascending=False).reset_index(drop=True)
    top = best.iloc[0]
    lines.append(f"- **Best overall by macro linear-probe AUROC**: **{top.space}** ({top.macro_auroc_linear:.3f}, kNN {top.macro_auroc_knn:.3f}, {top.n_labels_evaluated} labels evaluated).")
    lines.append("- **Full ranking**: " + "; ".join(f"{r.space} {r.macro_auroc_linear:.3f}" for r in best.itertuples()))
    dale_row = best[best.key == "dale"]
    if len(dale_row):
        d = dale_row.iloc[0]
        rank = int(best.index[best.key == "dale"][0]) + 1
        lines.append(f"- **DALE-CT-0 (1-channel, native)** ranks {rank} of {len(best)} ({d.macro_auroc_linear:.3f}); compare this directly against the best 3-channel strategy above to judge whether the 3-channel construction helps at all over the native 1-channel method.")
    if len(PAIR_DF):
        sig = PAIR_DF[PAIR_DF.p_fdr < 0.05]
        lines.append(f"- {len(sig)} of {len(PAIR_DF)} pairwise comparisons are significant after FDR correction (see `method_pairwise_stats.csv` for effect sizes and CIs).")
    lines.append("- Caution: labels are CT-RATE's own (automated) annotations, not independent ground truth. This notebook measures frozen-feature probe performance only - it says nothing about compute cost or how these methods generalise to a different scanner (see `CT_Domain_Gap_Analysis.ipynb` for that).")
else:
    lines.append("- No probe results (see section 8 for why).")
display(Markdown("**Findings**\n\n" + "\n".join(lines)))
SUMMARY["findings"] = lines
(OUTPUT_DIR / "summary.md").write_text("# Channel/backbone abnormality-recognition comparison\n\n" + "\n".join(lines) + "\n", encoding="utf-8")
(OUTPUT_DIR / "summary.json").write_text(json.dumps(SUMMARY, indent=1, default=float))
print("outputs written to", OUTPUT_DIR)

**Findings**

- **Best overall by macro linear-probe AUROC**: **DINOv2-S / adjacent** (0.675, kNN 0.625, 18 labels evaluated).
- **Full ranking**: DINOv2-S / adjacent 0.675; DINOv2-S / windows 0.674; DINOv2-S / same 0.673; DINOv3-S / adjacent 0.665; DINOv3-S / window_edge 0.663; DALE-CT-0 (1-channel, native) 0.663; DINOv3-S / windows 0.648; DINOv3-S / same 0.647; DINOv2-S / window_edge 0.639
- **DALE-CT-0 (1-channel, native)** ranks 6 of 9 (0.663); compare this directly against the best 3-channel strategy above to judge whether the 3-channel construction helps at all over the native 1-channel method.
- 2 of 36 pairwise comparisons are significant after FDR correction (see `method_pairwise_stats.csv` for effect sizes and CIs).
- Caution: labels are CT-RATE's own (automated) annotations, not independent ground truth. This notebook measures frozen-feature probe performance only - it says nothing about compute cost or how these methods generalise to a different scanner (see `CT_Domain_Gap_Analysis.ipynb` for that).

outputs written to /content/drive/MyDrive/NHRD - Local Sample/channel_encoding_outputs